### ISSUE TITLE
Model compilation troubles on MSVC 2010 x64

### ISSUE THREAD

**Issue by giumas** [stan-dev/pystan#127]
After some troubles, I got PyStan compiled with Python 3.4 using MSVC 2010.

When I attempt to run the example code in PyPi, I get these errors that stopped me since they are C++11 related and MSVC 2010 does not seem to support them:

```
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_7af71fe73cad6b7d51a4ce15383db4c6 NOW.
stanfit4anon_model_7af71fe73cad6b7d51a4ce15383db4c6_72626c303f8f7f625ed267bd0a87d664.cpp
c:\python34\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/acosh.hpp(70) : error C2039: 'acosh' : is not a member of '`global namespace''
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/acosh.hpp(70) : error C2664: 'stan::agrad::`anonymous-namespace'::acosh_vari::acosh_vari(double,stan::agrad::vari *)' : cannot convert parameter 1 from 'stan::agrad::var' to 'double'
        No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/asinh.hpp(68) : error C2039: 'asinh' : is not a member of '`global namespace''
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/asinh.hpp(68) : error C2664: 'stan::agrad::`anonymous-namespace'::asinh_vari::asinh_vari(double,stan::agrad::vari *)' : cannot convert parameter 1 from 'stan::agrad::var' to 'double'
        No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/atanh.hpp(70) : error C2039: 'atanh' : is not a member of '`global namespace''
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/atanh.hpp(70) : error C2664: 'stan::agrad::`anonymous-namespace'::atanh_vari::atanh_vari(double,stan::agrad::vari *)' : cannot convert parameter 1 from 'stan::agrad::var' to 'double'
        No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/bessel_first_kind.hpp(22) : warning C4244: 'argument' : conversion from 'double' to 'const int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/bessel_first_kind.hpp(22) : warning C4244: 'argument' : conversion from 'double' to 'const int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/bessel_second_kind.hpp(22) : warning C4244: 'argument' : conversion from 'double' to 'const int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/bessel_second_kind.hpp(22) : warning C4244: 'argument' : conversion from 'double' to 'const int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/cbrt.hpp(15) : error C2039: 'cbrt' : is not a member of '`global namespace''
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/cbrt.hpp(15) : error C3861: 'cbrt': identifier not found
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/erf.hpp(17) : error C2039: 'erf' : is not a member of '`global namespace''
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/erf.hpp(17) : error C3861: 'erf': identifier not found
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/erfc.hpp(18) : error C2039: 'erfc' : is not a member of '`global namespace''
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/erfc.hpp(18) : error C3861: 'erfc': identifier not found
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/expm1.hpp(17) : error C2039: 'expm1' : is not a member of '`global namespace''
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/expm1.hpp(17) : error C3861: 'expm1': identifier not found
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/fma.hpp(23) : error C3861: 'fma': identifier not found
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/fma.hpp(44) : error C2039: 'fma' : is not a member of '`global namespace''
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/fma.hpp(44) : error C3861: 'fma': identifier not found
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/fma.hpp(63) : error C2039: 'fma' : is not a member of '`global namespace''
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/fma.hpp(63) : error C3861: 'fma': identifier not found
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/fma.hpp(82) : error C2039: 'fma' : is not a member of '`global namespace''
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/fma.hpp(82) : error C3861: 'fma': identifier not found
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/fma.hpp(98) : error C2039: 'fma' : is not a member of '`global namespace''
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/fma.hpp(98) : error C3861: 'fma': identifier not found
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/modified_bessel_first_kind.hpp(19) : warning C4244: 'argument' : conversion from 'double' to 'const int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/modified_bessel_first_kind.hpp(19) : warning C4244: 'argument' : conversion from 'double' to 'const int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/modified_bessel_second_kind.hpp(19) : warning C4244: 'argument' : conversion from 'double' to 'const int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/modified_bessel_second_kind.hpp(19) : warning C4244: 'argument' : conversion from 'double' to 'const int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/owens_t.hpp(30) : error C2039: 'erf' : is not a member of '`global namespace''
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/owens_t.hpp(31) : error C2677: binary '+=' : no global operator found which takes type 'stan::agrad::var' (or there is no acceptable conversion)
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/owens_t.hpp(47) : error C2039: 'erf' : is not a member of '`global namespace''
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/owens_t.hpp(49) : error C2677: binary '+=' : no global operator found which takes type 'stan::agrad::var' (or there is no acceptable conversion)
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/trunc.hpp(16) : error C2039: 'trunc' : is not a member of '`global namespace''
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/functions/trunc.hpp(16) : error C3861: 'trunc': identifier not found
C:\Python34\lib\site-packages\pystan\stan/src\stan/mcmc/sample.hpp(27) : warning C4244: 'return' : conversion from '__int64' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/prob/welford_var_estimator.hpp(35) : warning C4244: 'return' : conversion from 'double' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/mcmc/windowed_adaptation.hpp(54) : warning C4244: '=' : conversion from 'double' to 'unsigned int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/mcmc/windowed_adaptation.hpp(55) : warning C4244: '=' : conversion from 'double' to 'unsigned int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/prob/welford_covar_estimator.hpp(35) : warning C4244: 'return' : conversion from 'double' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/common/print_progress.hpp(21) : warning C4244: 'initializing' : conversion from 'double' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/math/matrix/containers_conversion.hpp(78) : warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/math/matrix/containers_conversion.hpp(105) : warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/matrix/log_softmax.hpp(118) : warning C4244: 'argument' : conversion from '__int64' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/matrix/multiply_lower_tri_self_transpose.hpp(22) : warning C4244: 'initializing' : conversion from '__int64' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/matrix/multiply_lower_tri_self_transpose.hpp(23) : warning C4244: 'initializing' : conversion from '__int64' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/agrad/rev/matrix/softmax.hpp(87) : warning C4244: 'argument' : conversion from '__int64' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/io/cmd_line.hpp(32) : warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/list_argument.hpp(31) : warning C4373: 'stan::gm::list_argument::print': virtual function overrides 'stan::gm::valued_argument::print', previous versions of the compiler did not override when parameters only differed by const/volatile qualifiers
        C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/valued_argument.hpp(14) : see declaration of 'stan::gm::valued_argument::print'
C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/list_argument.hpp(36) : warning C4373: 'stan::gm::list_argument::print_help': virtual function overrides 'stan::gm::valued_argument::print_help', previous versions of the compiler did not override when parameters only differed by const/volatile qualifiers
        C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/valued_argument.hpp(26) : see declaration of 'stan::gm::valued_argument::print_help'
C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/list_argument.hpp(151) : warning C4373: 'stan::gm::list_argument::arg': virtual function overrides 'stan::gm::argument::arg', previous versions of the compiler did not override when parameters only differed by const/volatile qualifiers
        C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/argument.hpp(67) : see declaration of 'stan::gm::argument::arg'
C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/list_argument.hpp(79) : warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/list_argument.hpp(106) : warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/list_argument.hpp(116) : warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/arg_num_samples.hpp(21) : warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/arg_num_samples.hpp(22) : warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/arg_num_warmup.hpp(21) : warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/arg_num_warmup.hpp(22) : warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/arg_thin.hpp(21) : warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/arg_thin.hpp(22) : warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/arg_max_depth.hpp(21) : warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/arg_max_depth.hpp(22) : warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/arg_iter.hpp(21) : warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/arg_iter.hpp(22) : warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/arg_id.hpp(21) : warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/arg_id.hpp(22) : warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/arg_refresh.hpp(21) : warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
C:\Python34\lib\site-packages\pystan\stan/src\stan/gm/arguments/arg_refresh.hpp(22) : warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
C:\Users\gmasetti\AppData\Local\Temp\tmp_y6u7qke\pystan\stanfit4anon_model_7af71fe73cad6b7d51a4ce15383db4c6_72626c303f8f7f625ed267bd0a87d664.cpp(2813) : warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)
C:\Users\gmasetti\AppData\Local\Temp\tmp_y6u7qke\pystan\stanfit4anon_model_7af71fe73cad6b7d51a4ce15383db4c6_72626c303f8f7f625ed267bd0a87d664.cpp(3963) : warning C4267: '=' : conversion from 'size_t' to 'int', possible loss of data
C:\Users\gmasetti\AppData\Local\Temp\tmp_y6u7qke\pystan\stanfit4anon_model_7af71fe73cad6b7d51a4ce15383db4c6_72626c303f8f7f625ed267bd0a87d664.cpp(5739) : warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)
C:\Users\gmasetti\AppData\Local\Temp\tmp_y6u7qke\pystan\stanfit4anon_model_7af71fe73cad6b7d51a4ce15383db4c6_72626c303f8f7f625ed267bd0a87d664.cpp(5756) : warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)
C:\Users\gmasetti\AppData\Local\Temp\tmp_y6u7qke\pystan\stanfit4anon_model_7af71fe73cad6b7d51a4ce15383db4c6_72626c303f8f7f625ed267bd0a87d664.cpp(5810) : warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)
C:\Users\gmasetti\AppData\Local\Temp\tmp_y6u7qke\pystan\stanfit4anon_model_7af71fe73cad6b7d51a4ce15383db4c6_72626c303f8f7f625ed267bd0a87d664.cpp(5976) : warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)
C:\Users\gmasetti\AppData\Local\Temp\tmp_y6u7qke\pystan\stanfit4anon_model_7af71fe73cad6b7d51a4ce15383db4c6_72626c303f8f7f625ed267bd0a87d664.cpp(6045) : warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)
C:\Users\gmasetti\AppData\Local\Temp\tmp_y6u7qke\pystan\stanfit4anon_model_7af71fe73cad6b7d51a4ce15383db4c6_72626c303f8f7f625ed267bd0a87d664.cpp(6513) : warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)
C:\Users\gmasetti\AppData\Local\Temp\tmp_y6u7qke\pystan\stanfit4anon_model_7af71fe73cad6b7d51a4ce15383db4c6_72626c303f8f7f625ed267bd0a87d664.cpp(11134) : warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)
C:\Users\gmasetti\AppData\Local\Temp\tmp_y6u7qke\pystan\stanfit4anon_model_7af71fe73cad6b7d51a4ce15383db4c6_72626c303f8f7f625ed267bd0a87d664.cpp(11134) : warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)
C:\Users\gmasetti\AppData\Local\Temp\tmp_y6u7qke\pystan\stanfit4anon_model_7af71fe73cad6b7d51a4ce15383db4c6_72626c303f8f7f625ed267bd0a87d664.cpp(11311) : warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)
Traceback (most recent call last):
  File "C:\Python34\lib\distutils\msvc9compiler.py", line 533, in compile
    extra_postargs)
  File "C:\Python34\lib\distutils\ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "C:\Python34\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:\Python34\lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/CODE/_py_/repo/oceanopy/zibo/stats/think_bayes/test_pystan_240.py", line 38, in <module>
    iter=1000, chains=4)
  File "C:\Python34\lib\site-packages\pystan\api.py", line 370, in stan
    save_dso=save_dso, verbose=verbose)
  File "C:\Python34\lib\site-packages\pystan\model.py", line 305, in __init__
    build_extension.run()
  File "C:\Python34\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Python34\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self.build_extension(ext)
  File "C:\Python34\lib\distutils\command\build_ext.py", line 503, in build_extension
    depends=ext.depends)
  File "C:\Python34\lib\distutils\msvc9compiler.py", line 535, in compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2
```

**Comment by ariddell** [comment]
I'll close this for now in hopes that the new documentation will help.
