### ISSUE TITLE
Error running Eight Schools example

### ISSUE THREAD

**Issue by leoguelman** [stan-dev/pystan#204]
I'd appreciate any pointers to fix the error getting below when running Eight Schools:

```python
>>> fit = sm.sampling(data=schools_dat, iter=1000, chains=4)
Process SpawnPoolWorker-1:
Process SpawnPoolWorker-2:
Process SpawnPoolWorker-3:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'stanfit4anon_model_19a09b474d1901f191444eaf8a6b8ce2_1184497513344622333'
ModuleNotFoundError: No module named 'stanfit4anon_model_19a09b474d1901f191444eaf8a6b8ce2_1184497513344622333'
Traceback (most recent call last):
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'stanfit4anon_model_19a09b474d1901f191444eaf8a6b8ce2_1184497513344622333'
Process SpawnPoolWorker-5:
Traceback (most recent call last):
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'stanfit4anon_model_19a09b474d1901f191444eaf8a6b8ce2_1184497513344622333'
```

## System
macOS Big Sur 11.2

**Comment by riddell-stan** [comment]
It looks like you're using PyStan 2.x. This repository is for PyStan 3. PyStan 2 is no longer maintained. Since you're on macOS, you might consider trying PyStan 3.

You might also consider searching the archived PyStan 2 repository for a solution to your problem: https://github.com/stan-dev/pystan2
