### ISSUE TITLE
PyStan wont compile C++ code Windows 10

### ISSUE THREAD

**Issue by JonnyCBB** [stan-dev/pystan#246]
#### Summary:
My version of PyStan won't correctly compile the C++ Code for the model that I enter (the **Eight Schools** example on the docs page).

#### Description:
I tried running the **Eight Schools** example within an IPython environment after installing pystan and it returns the error below.

#### Reproducible Steps:
I'm using Windows 10 and I've followed the installation instructions that [recommend Anaconda and VS 2008](http://pystan.readthedocs.io/en/latest/windows.html#windows). Then I installed pystan using the line `conda install -c patricksnape pystan` as given in the installation instructions. This was successful. Finally I opened an IPython REPL using the `ipython` command then I input the python commands as can be seen below.

#### Current Output:
```
In [1]: import pystan

In [2]: schools_code = """
   ...: data {
   ...:     int<lower=0> J; // number of schools
   ...:     real y[J]; // estimated treatment effects
   ...:     real<lower=0> sigma[J]; // s.e. of effect estimates
   ...: }
   ...: parameters {
   ...:     real mu;
   ...:     real<lower=0> tau;
   ...:     real eta[J];
   ...: }
   ...: transformed parameters {
   ...:     real theta[J];
   ...:     for (j in 1:J)
   ...:     theta[j] <- mu + tau * eta[j];
   ...: }
   ...: model {
   ...:     eta ~ normal(0, 1);
   ...:     y ~ normal(theta, sigma);
   ...: }
   ...: """
   ...:
   ...: schools_dat = {'J': 8,
   ...:                'y': [28,  8, -3,  7, -1,  1, 18, 12],
   ...:                'sigma': [15, 10, 16, 11,  9, 11, 10, 18]}
   ...:
   ...: fit = pystan.stan(model_code=schools_code, data=schools_dat,
   ...:                   iter=1000, chains=4)
   ...:
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_95013624776d537c3cd7cd4d641c30e0 NOW.
---------------------------------------------------------------------------
CompileError                              Traceback (most recent call last)
<ipython-input-2-0458b1590083> in <module>()
     26
     27 fit = pystan.stan(model_code=schools_code, data=schools_dat,
---> 28                   iter=1000, chains=4)

C:\Users\jonathan\Anaconda\lib\site-packages\pystan\api.pyc in stan(file, model_name, model_code, fit, data, pars, chains, iter, warmup, thin, init, seed, algor
ithm, control, sample_file, diagnostic_file, save_dso, verbose, boost_lib, eigen_lib, n_jobs, **kwargs)
    371         m = StanModel(file=file, model_name=model_name, model_code=model_code,
    372                       boost_lib=boost_lib, eigen_lib=eigen_lib,
--> 373                       save_dso=save_dso, verbose=verbose)
    374     # check that arguments in kwargs are valid
    375     valid_args = {"chain_id", "init_r", "test_grad", "append_samples", "enable_random_init",

C:\Users\jonathan\Anaconda\lib\site-packages\pystan\model.pyc in __init__(self, file, charset, model_name, model_code, stanc_ret, boost_lib, eigen_lib, save_dso
, verbose, obfuscate_model_name)
    315
    316         try:
--> 317             build_extension.run()
    318         finally:
    319             if redirect_stderr:

C:\Users\jonathan\Anaconda\lib\distutils\command\build_ext.pyc in run(self)
    337
    338         # Now actually compile and link everything.
--> 339         self.build_extensions()
    340
    341     def check_extensions_list(self, extensions):

C:\Users\jonathan\Anaconda\lib\distutils\command\build_ext.pyc in build_extensions(self)
    446
    447         for ext in self.extensions:
--> 448             self.build_extension(ext)
    449
    450     def build_extension(self, ext):

C:\Users\jonathan\Anaconda\lib\distutils\command\build_ext.pyc in build_extension(self, ext)
    496                                          debug=self.debug,
    497                                          extra_postargs=extra_args,
--> 498                                          depends=ext.depends)
    499
    500         # XXX -- this is a Vile HACK!

C:\Users\jonathan\Anaconda\lib\distutils\ccompiler.pyc in compile(self, sources, output_dir, macros, include_dirs, debug, extra_preargs, extra_postargs, depends
)
    572             except KeyError:
    573                 continue
--> 574             self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    575
    576         # Return *all* object filenames, not just the ones we just built.

C:\Users\jonathan\Anaconda\lib\distutils\cygwinccompiler.pyc in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
    164                            extra_postargs)
    165             except DistutilsExecError, msg:
--> 166                 raise CompileError, msg
    167
    168     def link (self,

CompileError: command 'C:\\Users\\jonathan\\Anaconda\\Scripts\\gcc.bat' failed with exit status 1
```

#### Expected Output:
Whatever the expected output is from the **Eight Schools** example on the docs page

#### Operating System: Windows 10

Any help would be much appreciated.

**Comment by ariddell** [comment]
PyStan now works (and is tested) with Windows and Python 3.5. If you use Python 3.5 you don't need Anaconda and can just use ``pip install pystan``.

The instructions do need to be updated since, going forward, Windows is only going to be supported when used with Python 3.5 or higher.

It would be great to have some feedback from someone trying to install PyStan using this method.

**Comment by JonnyCBB** [comment]
Sorry for late reply. We just tested PyStan using an Anaconda distribution with Python 3.5 on Windows 7 on a friend's laptop and it didn't work straight off. Here's what we typed (after doing a `pip install pystan`):
```python
import pystan

schools_code = """
data {
    int<lower=0> J; // number of schools
    real y[J]; // estimated treatment effects
    real<lower=0> sigma[J]; // s.e. of effect estimates
}
parameters {
    real mu;
    real<lower=0> tau;
    real eta[J];
}
transformed parameters {
    real theta[J];
    for (j in 1:J)
    theta[j] <- mu + tau * eta[j];
}
model {
    eta ~ normal(0, 1);
    y ~ normal(theta, sigma);
}
"""

schools_dat = {'J': 8,
               'y': [28,  8, -3,  7, -1,  1, 18, 12],
               'sigma': [15, 10, 16, 11,  9, 11, 10, 18]}

fit = pystan.stan(model_code=schools_code, data=schools_dat,
                  iter=1000, chains=4)
```
i.e. it's the same as before, but we get the following error:
```
Traceback (most recent call last):

  File "<ipython-input-2-8ca3435de725>", line 28, in <module>
    iter=1000, chains=4)

  File "C:\Anaconda3\lib\site-packages\pystan\api.py", line 372, in stan
    verbose=verbose)

  File "C:\Anaconda3\lib\site-packages\pystan\model.py", line 310, in __init__
    build_extension.run()

  File "C:\Anaconda3\lib\distutils\command\build_ext.py", line 338, in run
    self.build_extensions()

  File "C:\Anaconda3\lib\distutils\command\build_ext.py", line 447, in build_extensions
    self._build_extensions_serial()

  File "C:\Anaconda3\lib\distutils\command\build_ext.py", line 472, in _build_extensions_serial
    self.build_extension(ext)

  File "C:\Anaconda3\lib\distutils\command\build_ext.py", line 532, in build_extension
    depends=ext.depends)

  File "C:\Anaconda3\lib\distutils\_msvccompiler.py", line 306, in compile
    self.initialize()

  File "C:\Anaconda3\lib\distutils\_msvccompiler.py", line 199, in initialize
    vc_env = _get_vc_env(plat_spec)

  File "C:\Anaconda3\lib\distutils\_msvccompiler.py", line 85, in _get_vc_env
    raise DistutilsPlatformError("Unable to find vcvarsall.bat")

DistutilsPlatformError: Unable to find vcvarsall.bat
```

**Comment by JonnyCBB** [comment]
I've got a friend who's sent a solution for Python 2.7 on Windows so I'm about to test that and I'll let you know how it goes.

**Comment by JonnyCBB** [comment]
I tried his solution and it didn't work for me. He the error above which he was able to sort out.

**Comment by ariddell** [comment]
I don't have access to a Windows machine right now but I will in a few weeks. The Windows instructions definitely need to be updated before the next release.

Sorry I can't help more. I think the main tasks are

1. Install the C++ compiler Microsoft will let you install for free.
2. Use Python 3.5

**Comment by ariddell** [comment]
I've tested installation on Windows 7 and can verify the instructions work. @JonnyCBB if you'd like to give the instructions a spin you can see them right now at the commit https://github.com/stan-dev/pystan/blob/5165feb1a5e6a17285ab11a640a943abbae0c1ff/doc/windows.rst

**Comment by sursu** [comment]
@ariddell From that link, it is not clear to me whether it is possible to make it run on Windows 10 or not?
I manage to install pystan. But it does not run properly.

> INFO:pystan:COMPILING THE C++ CODE FOR MODEL

gives me errors, as you might have guessed already.

**Comment by ahartikainen** [comment]
Hi, please see this issue (#364) for the updated instructions for windows.

https://github.com/stan-dev/pystan/issues/364

**Comment by zeki-kadiroglu** [comment]
https://pystan.readthedocs.io/en/latest/windows.html  --follow the these  steps to  overcome that problems .
