### ISSUE TITLE
data int32 JSON issue

### ISSUE THREAD

**Issue by dirknbr** [stan-dev/pystan#272]
I am surprised I have this issue for the first time

freq is a np.int32 array of integers

``` 
freq = np.random.poisson(1.5, size=N).astype(np.int32)

data = {'N': N, 'K': max(freq), 'freq': freq, 'spend': spend, 'X': X}
stancode = open('....stan').read()
model = stan.build(stancode, data)

Traceback (most recent call last):
  File "/home/dnachbar/python/mv_poisson/own.py", line 16, in <module>
    model = stan.build(stancode, data)
  File "/home/dnachbar/.local/lib/python3.9/site-packages/stan/model.py", line 424, in build
    data = json.loads(DataJSONEncoder().encode(data))
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/dnachbar/.local/lib/python3.9/site-packages/stan/model.py", line 27, in default
    return json.JSONEncoder.default(self, obj)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int32 is not JSON serializable

```

**Comment by ahartikainen** [comment]
Transform `max(freq)` to `int(max(freq))`

**Comment by dirknbr** [comment]
it worked, thanks
