### ISSUE TITLE
Running inside an async function

### ISSUE THREAD

**Issue by hugbubby** [stan-dev/pystan#279]
Currently pystan tries to run asyncio.run() itself, which prevents any asynchronous program from using the build or sample functions. I'm trying to get it to work with some nasty wrapper code right now.

You should be able to detect if this is happening and avoid the asyncio.run() call, instead using the main event loop. I don't know enough about python to tell you how to do it. It's definitely _not_ a problem with Jupyter Notebook, your library just shouldn't require itself to be run in non-asynchronous functions or (better yet) should be asynchronous itself. We _cannot_ disable the multiprocessing as it makes sampling prohibitively slow for our production use case, though I'm not sure if the asynchronousness in pystan is actually a bottleneck for anything or if the C++ stan library does all the multithreading itself.

**Comment by ahartikainen** [comment]
If you need to run pystan in async environment, can you use `nest-asyncio` solution?

One option is to run pystan in a thread, see the following example which has wrapped specific parts in the codebase.

https://github.com/ahartikainen/pystan-jupyter

https://pypi.org/project/pystan-jupyter

**Comment by hugbubby** [comment]
I tried pystan-jupyter but I got the following as output:
```
Exception in callback handle_create_fit.<locals>._services_call_done({'done': True, 'metadata': {'fit': {'name': 'models/tcjbu...fits/tn6zqtqv'}}, 'name': 'operations/tn6zqtqv', 'result': {'code': 400, 'message': "Exception du...broke
n)\\n']`", 'status': 'Bad Request'}})(<Task finishe...ble anymore')>) at /usr/local/lib/python3.9/site-packages/httpstan/views.py:367
handle: <Handle handle_create_fit.<locals>._services_call_done({'done': True, 'metadata': {'fit': {'name': 'models/tcjbu...fits/tn6zqtqv'}}, 'name': 'operations/tn6zqtqv', 'result': {'code': 400, 'message': "Exception du...broken)\\n'
]`", 'status': 'Bad Request'}})(<Task finishe...ble anymore')>) at /usr/local/lib/python3.9/site-packages/httpstan/views.py:367>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/site-packages/httpstan/views.py", line 392, in _services_call_done
    self._context.run(self._callback, *self._args)                                                                                                                                                                                 [0/635]
  File "/usr/local/lib/python3.9/site-packages/httpstan/views.py", line 392, in _services_call_done
    httpstan.cache.delete_fit(operation["metadata"]["fit"]["name"])
  File "/usr/local/lib/python3.9/site-packages/httpstan/cache.py", line 140, in delete_fit
    path.unlink()
  File "/usr/local/lib/python3.9/pathlib.py", line 1343, in unlink
    self._accessor.unlink(self)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/httpstan/4.4.2/models/tcjbuxhp/fits/tn6zqtqv.jsonlines.lz4'
Exception in callback handle_create_fit.<locals>._services_call_done({'done': True, 'metadata': {'fit': {'name': 'models/tcjbu...fits/ksumbyjf'}}, 'name': 'operations/ksumbyjf', 'result': {'code': 400, 'message': "Exception du...broke
n)\\n']`", 'status': 'Bad Request'}})(<Task finishe...ble anymore')>) at /usr/local/lib/python3.9/site-packages/httpstan/views.py:367
handle: <Handle handle_create_fit.<locals>._services_call_done({'done': True, 'metadata': {'fit': {'name': 'models/tcjbu...fits/ksumbyjf'}}, 'name': 'operations/ksumbyjf', 'result': {'code': 400, 'message': "Exception du...broken)\\n'
]`", 'status': 'Bad Request'}})(<Task finishe...ble anymore')>) at /usr/local/lib/python3.9/site-packages/httpstan/views.py:367>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/site-packages/httpstan/views.py", line 392, in _services_call_done
    httpstan.cache.delete_fit(operation["metadata"]["fit"]["name"])
  File "/usr/local/lib/python3.9/site-packages/httpstan/cache.py", line 140, in delete_fit
    path.unlink()
  File "/usr/local/lib/python3.9/pathlib.py", line 1343, in unlink
    self._accessor.unlink(self)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/httpstan/4.4.2/models/tcjbuxhp/fits/ksumbyjf.jsonlines.lz4'
Traceback (most recent call last):
  File "/code/./main.py", line 325, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/code/./main.py", line 322, in main
    await asyncio.gather(model(), startApp())
  File "/code/./main.py", line 249, in model
    await update()
  File "/code/./main.py", line 242, in update
    fit = exec_async(mod.sample,num_chains=4)
  File "/code/./main.py", line 10, in exec_async
    return future.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/stan/model.py", line 84, in sample
    return self.hmc_nuts_diag_e_adapt(num_chains=num_chains, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/stan/model.py", line 104, in hmc_nuts_diag_e_adapt
    return self._create_fit(kwargs)
  File "/usr/local/lib/python3.9/site-packages/stan/model.py", line 291, in _create_fit
    return asyncio.run(go())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/stan/model.py", line 221, in go
    raise RuntimeError(operation["result"]["message"])
RuntimeError: Exception during call to services function: `BrokenProcessPool('A process in the process pool was terminated abruptly while the future was running or pending.')`, traceback: `['  File "/usr/local/lib/python3.9/site-packa
ges/httpstan/services_stub.py", line 153, in call\n    future.result()\n']`

```

**Comment by riddell-stan** [comment]
What docker container? If you're using the wheels, pystan requires very recent C++ compilers.

**Comment by riddell-stan** [comment]
I'm going to close this and create a new issue (#280) for the asyncio issue. I'm confident the docker bug is not related to the asyncio issue.
