### ISSUE TITLE
cannot compile model

### ISSUE THREAD

**Issue by moobb** [stan-dev/pystan#283]
cannot copile model. have seen similar issues described but couldn't see a solution. Running ubuntu, configuration below. Many thanks

Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
numpy  1.11.2 py35_0  
cython 0.25.2 py35_0  

>>> fit = pystan.stan(model_code=schools_code, data=schools_dat, iter=1000, chains=4)
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_95013624776d537c3cd7cd4d641c30e0 NOW.
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/m/anaconda3/lib/python3.5/site-packages/pystan/api.py", line 368, in stan
    verbose=verbose)
  File "/home/m/anaconda3/lib/python3.5/site-packages/pystan/model.py", line 315, in __init__
    self.module = load_module(module_name, lib_dir)
  File "/home/m/anaconda3/lib/python3.5/site-packages/pystan/model.py", line 50, in load_module
    return loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: /tmp/tmp1t5bt42f/pystan/stanfit4anon_model_95013624776d537c3cd7cd4d641c30e0_d5a1d5f1585818b4684cf19b1e9e4e54.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZNSt8ios_base7failureB5cxx11D1Ev

**Comment by ariddell** [comment]
It's the new Cython. This will be fixed in the next release.
