### ISSUE TITLE
Can't run `stan.build` in a Jupyter notebook

### ISSUE THREAD

**Issue by ForceBru** [stan-dev/pystan#311]
#### Describe the bug

The error message is the same as here: https://github.com/stan-dev/pystan/issues/280. This comment (https://github.com/stan-dev/pystan/issues/280#issuecomment-828733049) says that "this is not a typical use of pystan", but... isn't a Jupyter notebook literally _the_ most typical use of [insert any data science library, including PyStan]??

Error message:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-43aaeb297283> in <module>
----> 1 posterior = stan.build("", data=data, random_seed=1)

~/opt/miniconda3/lib/python3.9/site-packages/stan/model.py in build(program_code, data, random_seed)
    510 
    511     try:
--> 512         return asyncio.run(go())
    513     except KeyboardInterrupt:
    514         return  # type: ignore

~/opt/miniconda3/lib/python3.9/asyncio/runners.py in run(main, debug)
     31     """
     32     if events._get_running_loop() is not None:
---> 33         raise RuntimeError(
     34             "asyncio.run() cannot be called from a running event loop")
     35 

RuntimeError: asyncio.run() cannot be called from a running event loop
```

#### Describe your system

- macOS Catalina 10.15.7
- x86-64
- Apple clang version 12.0.0 (clang-1200.0.32.29)
- Python distribution:
   ```
   Python 3.9.5 (default, May 18 2021, 12:31:01) 
  [Clang 10.0.0 ] :: Anaconda, Inc. on darwin
  ```
- Some package versions
   ```
   $ conda list                                                                             (base) 
   # packages in environment at /Users/forcebru/opt/miniconda3:
   #
   # Name                    Version                   Build  Channel
   httpstan                  4.5.0                    pypi_0    pypi
   ipykernel                 5.5.5            py39h71a6800_0    conda-forge
   ipython                   7.22.0           py39h71a6800_0    conda-forge
   ipython_genutils          0.2.0                      py_1    conda-forge
   ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
   jupyter                   1.0.0            py39h6e9494a_6    conda-forge
   jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
   jupyter_console           6.4.0              pyhd8ed1ab_0    conda-forge
   jupyter_core              4.7.1            py39h6e9494a_0    conda-forge
   jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
   jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
   nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
   nbconvert                 6.0.7            py39h6e9494a_3    conda-forge
   nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
   ncurses                   6.2                  h2e338ed_4    conda-forge
   nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
   ninja                     1.10.2               h9a9d8cb_0    conda-forge
   notebook                  6.4.0              pyha770c72_0    conda-forge
   nspr                      4.30                 hcd9eead_0    conda-forge
   nss                       3.66                 h31e2bf1_0    conda-forge
   numpy                     1.20.3           py39h7eed0ac_1    conda-forge
   pylev                     1.4.0                    pypi_0    pypi
   pysimdjson                3.2.0                    pypi_0    pypi
   pystan                    3.2.0                    pypi_0    pypi
   python                    3.9.5                h88f2d9e_3  
   ```

#### Code Sample, a copy-pastable example

Code adapted from [this STAN case study](https://mc-stan.org/users/documentation/case-studies/identifying_mixture_models.html):

```python
import stan
import numpy as np

N = 1000
mu = np.array([-.2, .2])
Z = np.random.binomial(1, .3, N)
Y = np.random.normal(mu[Z])

data = {
    'N': Y.size,
    'y': Y
}

posterior = stan.build("", data=data, random_seed=1)
```

This works when pasted into the REPL, but raises a very non-descriptive error message (I guess that's because the script is an empty string?):

```python
Python 3.9.5 (default, May 18 2021, 12:31:01) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import stan
>>> import numpy as np
>>> N = 1000
>>> mu = np.array([-.2, .2])
>>> Z = np.random.binomial(1, .3, N)
>>> Y = np.random.normal(mu[Z])
>>> data = {
...     'N': Y.size,
...     'y': Y
... }
>>> posterior = stan.build("", data=data, random_seed=1)
Building: 56.6s, done.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/forcebru/opt/miniconda3/lib/python3.9/site-packages/stan/model.py", line 512, in build
    return asyncio.run(go())
  File "/Users/forcebru/opt/miniconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/forcebru/opt/miniconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/forcebru/opt/miniconda3/lib/python3.9/site-packages/stan/model.py", line 507, in go
    param_names, dims = zip(*((param["name"], param["dims"]) for param in params_list))
ValueError: not enough values to unpack (expected 2, got 0)
>>> 
```

**Comment by ahartikainen** [comment]
Hi, use nest-asyncio.

https://pystan.readthedocs.io/en/latest/faq.html#how-can-i-use-pystan-with-jupyter-notebook-or-jupyterlab

**Comment by ForceBru** [comment]
Oh, I even read about getting parameter summary statistics _on that same page_, but somehow completely missed the part about Jupyter notebooks... Sorry about that

**Comment by ahartikainen** [comment]
No harm was made. Thanks for using pystan.
