### ISSUE TITLE
Error building a model

### ISSUE THREAD

**Issue by carolfs** [stan-dev/pystan#324]
#### Describe the bug
I am getting an error trying to build a model. The model builds fine with `cmdstanpy`, so I don't think there's anything wrong with it. The error:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-7895294d39b6> in <module>
----> 1 sm = stan.build(model, data=model_dat)

~/.local/lib/python3.9/site-packages/stan/model.py in build(program_code, data, random_seed)
    510 
    511     try:
--> 512         return asyncio.run(go())
    513     except KeyboardInterrupt:
    514         return  # type: ignore

/usr/lib64/python3.9/asyncio/runners.py in run(main, debug)
     42         if debug is not None:
     43             loop.set_debug(debug)
---> 44         return loop.run_until_complete(main)
     45     finally:
     46         try:

/usr/lib64/python3.9/asyncio/base_events.py in run_until_complete(self, future)
    640             raise RuntimeError('Event loop stopped before Future completed.')
    641 
--> 642         return future.result()
    643 
    644     def stop(self):

~/.local/lib/python3.9/site-packages/stan/model.py in go()
    479                 match = re.search(r"""ValueError\(['"](.*)['"]\)""", resp.json()["message"])
    480                 if not match:  # unknown error, should not happen
--> 481                     raise RuntimeError(resp.json()["message"])
    482                 exception_body = match.group(1).encode().decode("unicode_escape")
    483                 error_type_match = re.match(r"(Semantic|Syntax) error", exception_body)

RuntimeError: Exception while building model extension module: `CompileError(DistutilsExecError("command '/usr/bin/gcc' failed with exit code 1"))`, traceback: `['  File "/home/carolfs/.local/lib/python3.9/site-packages/httpstan/views.py", line 114, in handle_create_model\n    compiler_output = await httpstan.models.build_services_extension_module(program_code)\n', '  File "/home/carolfs/.local/lib/python3.9/site-packages/httpstan/models.py", line 168, in build_services_extension_module\n    compiler_output = await asyncio.get_running_loop().run_in_executor(\n', '  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 52, in run\n    result = self.fn(*self.args, **self.kwargs)\n', '  File "/home/carolfs/.local/lib/python3.9/site-packages/httpstan/build_ext.py", line 80, in run_build_ext\n    build_extension.run()\n', '  File "/usr/lib64/python3.9/distutils/command/build_ext.py", line 340, in run\n    self.build_extensions()\n', '  File "/usr/lib64/python3.9/distutils/command/build_ext.py", line 449, in build_extensions\n    self._build_extensions_serial()\n', '  File "/usr/lib64/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial\n    self.build_extension(ext)\n', '  File "/usr/lib64/python3.9/distutils/command/build_ext.py", line 529, in build_extension\n    objects = self.compiler.compile(sources,\n', '  File "/usr/lib64/python3.9/distutils/ccompiler.py", line 574, in compile\n    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)\n', '  File "/usr/lib64/python3.9/distutils/unixccompiler.py", line 129, in _compile\n    raise CompileError(msg)\n']`
```

#### Describe your system
Fedora 34, x86-64, g++ (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1), Python 3.9.7

#### Code Sample, a copy-pastable example

```
import stan
model = stan.build(open("my_model.stan").read(), data=model_dat)
```

**Comment by riddell-stan** [comment]
Thanks for the report. Can you tell us more about your setup. Are you using conda? Jupyter notebook?

**Comment by carolfs** [comment]
No to both, just running the code above from ipython.

**Comment by carolfs** [comment]
Here is the model code. I changed the variable names, don't worry, I normally don't name my variables like this.

```
functions {
    real func1(int bar, real[] qxyzs) {
        if (bar == 1) {
            return fmax(qxyzs[1], qxyzs[2]);
        }
        else if (bar == 2) {
            return fmax(qxyzs[3], qxyzs[1]);
        }
        else {
            return fmax(qxyzs[2], qxyzs[3]);
        }
    }
    real func2(int bar, real tp6, real[] qxyzs, real[] qbars) {
        return tp6 * func1(bar, qxyzs) + (1 - tp6) * qbars[bar];
    }
    real func3(int foo, real[] qxyzs) {
        return qxyzs[(foo - 1) % 3 + 1];
    }
    real func4(int foo, real tp7, real[] qxyzs, real[] qfoos) {
        return tp7 * func3(foo, qxyzs) + (1 - tp7) * qfoos[foo];
    }
    real my_loglik(int M, int[] data1, int[] data2, int[] data3, int[] data4, int[] data5, int[] data6,
        real[] data7, real tp1, real tp2, real tp3, real tp4, real tp5, real tp6, real tp7, real tp8) {
        real qxyzs[3] = rep_array(0., 3);
        real qfoos[6] = rep_array(0., 6);
        real qbars[3] = rep_array(0., 3);
        real ll = 0.0;
        for (t in 1:M) {
            real dxyz = data7[t] - qxyzs[data6[t]];
            real dfoo = qxyzs[data6[t]] - qfoos[data5[t]];
            if (data1[t]) {
                int foos[2] = {2*data4[t] - 1, 2*data4[t]};
                real dbar = qfoos[data5[t]] - qbars[data4[t]];
                if (data4[t] == data2[t]) {
                    ll += log_inv_logit(tp2*(
                        func2(data2[t], tp6, qxyzs, qbars) - 
                        func2(data3[t], tp6, qxyzs, qbars)
                    ));
                }
                else {
                    ll += log_inv_logit(tp2*(
                        func2(data3[t], tp6, qxyzs, qbars) - 
                        func2(data2[t], tp6, qxyzs, qbars)
                    ));
                }
                if (data5[t] == foos[1]) {
                    ll += log_inv_logit(tp3*(
                        func4(foos[1], tp7, qxyzs, qfoos) -
                        func4(foos[2], tp7, qxyzs, qfoos)
                    ));
                }
                else {
                    ll += log_inv_logit(tp3*(
                        func4(foos[2], tp7, qxyzs, qfoos) -
                        func4(foos[1], tp7, qxyzs, qfoos)
                    ));
                }
                qbars[data4[t]] += tp1 * dbar + tp5 * tp1 * dfoo + tp5^2 * tp1 * dxyz;
            }
            else {
                int foos[3] = (data5[t] % 2 == 0) ? {2, 4, 6} : {1, 3, 5};
                real foovals[3];
                for (i in 1:3) {
                    foovals[i] = tp4*func4(foos[i], tp8, qxyzs, qfoos);
                }
                ll += foovals[(data5[t] - 1)/2 + 1] - log_sum_exp(foovals);
            }
            qfoos[data5[t]] += tp1 * dfoo + tp5 * tp1 * dxyz;
            qxyzs[data6[t]] += tp1 * dxyz;
        }
        return ll;
    }
}
data {
    int N;
    int M[N];
    int P;
    int data1[N, P];
    int data2[N, P];
    int data3[N, P];
    int data4[N, P];
    int data5[N, P];
    int data6[N, P];
    real data7[N, P];
}
parameters {
    vector[8] my_params[N];
    vector<lower=0>[8] sigma;
    vector[8] mu;
}
model {
    real tp1[N];
    real tp2[N];
    real tp3[N];
    real tp4[N];
    real tp5[N];
    real tp6[N];
    real tp7[N];
    real tp8[N];
    for (i in 1:N) {
        tp1[i] = inv_logit(my_params[i][1]);
        tp2[i] = exp(my_params[i][2]);
        tp3[i] = exp(my_params[i][3]);
        tp4[i] = exp(my_params[i][4]);
        tp5[i] = inv_logit(my_params[i][5]);
        tp6[i] = inv_logit(my_params[i][6]);
        tp7[i] = inv_logit(my_params[i][7]);
        tp8[i] = inv_logit(my_params[i][8]);
    }
    mu ~ cauchy(0, 5);
    sigma ~ cauchy(0, 5);
    for (i in 1:N) {
        my_params[i] ~ student_t(4, mu, sigma);
        target += my_loglik(M[i], data1[i], data2[i], data3[i], data4[i], data5[i], data6[i],
            data7[i], tp1[i], tp2[i], tp3[i], tp4[i], tp5[i], tp6[i], tp7[i], tp8[i]);
    }
}
```

**Comment by riddell-stan** [comment]
I see what this is. It's https://github.com/stan-dev/httpstan/issues/566 (aka https://github.com/stan-dev/stanc3/pull/869 ).

This will be fixed when pystan starts using a newer stanc3 (which includes the fix).

You can fix this by addressing this warning message:

```
Info: Found int division at '/tmp/httpstan_ccnuzenp/model_y2wcoelt.stan', line 67, column 30 to column 44:
  (data5[t] - 1) / 2
Values will be rounded towards zero. If rounding is not desired you can write
the division as
  (data5[t] - 1) / 2.0
```

**Comment by carolfs** [comment]
Thanks! Rounding towards zero is the desired behaviour, so I'm not sure how to address the warning message. Using `cmdstanpy` for now.

**Comment by riddell-stan** [comment]
@carolfs looks like there should be a new release soon.

If you want a quick fix, I think you could use floating point division followed by `floor`. Might work.
