### ISSUE TITLE
AttributeError: __exit__ when n_jobs != 1

### ISSUE THREAD

**Issue by monga** [stan-dev/pystan#331]
#### Summary:

pystan 2.15 raises an `AttributeError` exception when `n_jobs=-1`: the same program runs without problems with pystan 2.15

It works with `n_jobs=1`. 

#### Description:
With the standard example:

```python
import pystan
schools_code = """
data {
    int<lower=0> J; // number of schools
    real y[J]; // estimated treatment effects
    real<lower=0> sigma[J]; // s.e. of effect estimates
}
parameters {
    real mu;
    real<lower=0> tau;
    real eta[J];
}
transformed parameters {
    real theta[J];
    for (j in 1:J)
    theta[j] = mu + tau * eta[j];
}
model {
    eta ~ normal(0, 1);
    y ~ normal(theta, sigma);
}
"""

schools_dat = {'J': 8,
               'y': [28,  8, -3,  7, -1,  1, 18, 12],
               'sigma': [15, 10, 16, 11,  9, 11, 10, 18]}

fit = pystan.stan(model_code=schools_code, data=schools_dat,
                  iter=1000, chains=4, n_jobs=-1)
```

pystan 2.15 (with python 2.7.13) gives the following:

```
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_cbe9cd2f1e5ab5d1c7cce1f23ca970b4 NOW.
Traceback (most recent call last):
  File "pystan-debug.py", line 29, in <module>
    iter=1000, chains=4, n_jobs=-1)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/pystan/api.py", line 395, in stan
    n_jobs=n_jobs, **kwargs)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/pystan/model.py", line 721, in sampling
    ret_and_samples = _map_parallel(call_sampler_star, call_sampler_args, n_jobs)
  File "/opt/conda/envs/python2/lib/python2.7/site-packages/pystan/model.py", line 79, in _map_parallel
    with multiprocessing.Pool(processes=n_jobs) as pool:
AttributeError: __exit__
```

#### Reproducible Steps:

```sh
cat << EOF > pystan-debug.py
import pystan
schools_code = """
data {
    int<lower=0> J; // number of schools
    real y[J]; // estimated treatment effects
    real<lower=0> sigma[J]; // s.e. of effect estimates
}
parameters {
    real mu;
    real<lower=0> tau;
    real eta[J];
}
transformed parameters {
    real theta[J];
    for (j in 1:J)
    theta[j] = mu + tau * eta[j];
}
model {
    eta ~ normal(0, 1);
    y ~ normal(theta, sigma);
}
"""

schools_dat = {'J': 8,
               'y': [28,  8, -3,  7, -1,  1, 18, 12],
               'sigma': [15, 10, 16, 11,  9, 11, 10, 18]}

fit = pystan.stan(model_code=schools_code, data=schools_dat,
                  iter=1000, chains=4, n_jobs=-1)
EOF
python pystan-debug.py

```

#### Expected Output:

This is the output with pystan 2.14

```
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_cbe9cd2f1e5ab5d1c7cce1f23ca970b4 NOW.
Iteration:   1 / 1000 [  0%]  (Warmup) (Chain 1)
Iteration:   1 / 1000 [  0%]  (Warmup) (Chain 0)
Iteration:   1 / 1000 [  0%]  (Warmup) (Chain 2)
Iteration:   1 / 1000 [  0%]  (Warmup) (Chain 3)
Iteration: 100 / 1000 [ 10%]  (Warmup) (Chain 0)
Iteration: 100 / 1000 [ 10%]  (Warmup) (Chain 1)
Iteration: 100 / 1000 [ 10%]  (Warmup) (Chain 2)
Iteration: 100 / 1000 [ 10%]  (Warmup) (Chain 3)
Iteration: 200 / 1000 [ 20%]  (Warmup) (Chain 1)
Iteration: 200 / 1000 [ 20%]  (Warmup) (Chain 0)
Iteration: 200 / 1000 [ 20%]  (Warmup) (Chain 2)
Iteration: 200 / 1000 [ 20%]  (Warmup) (Chain 3)
Iteration: 300 / 1000 [ 30%]  (Warmup) (Chain 0)
Iteration: 300 / 1000 [ 30%]  (Warmup) (Chain 1)
Iteration: 300 / 1000 [ 30%]  (Warmup) (Chain 2)
Iteration: 400 / 1000 [ 40%]  (Warmup) (Chain 0)
Iteration: 300 / 1000 [ 30%]  (Warmup) (Chain 3)
Iteration: 400 / 1000 [ 40%]  (Warmup) (Chain 1)
Iteration: 500 / 1000 [ 50%]  (Warmup) (Chain 0)
Iteration: 501 / 1000 [ 50%]  (Sampling) (Chain 0)
Iteration: 400 / 1000 [ 40%]  (Warmup) (Chain 2)
Iteration: 400 / 1000 [ 40%]  (Warmup) (Chain 3)
Iteration: 500 / 1000 [ 50%]  (Warmup) (Chain 1)
Iteration: 501 / 1000 [ 50%]  (Sampling) (Chain 1)
Iteration: 600 / 1000 [ 60%]  (Sampling) (Chain 0)
Iteration: 500 / 1000 [ 50%]  (Warmup) (Chain 2)
Iteration: 501 / 1000 [ 50%]  (Sampling) (Chain 2)
Iteration: 500 / 1000 [ 50%]  (Warmup) (Chain 3)
Iteration: 501 / 1000 [ 50%]  (Sampling) (Chain 3)
Iteration: 600 / 1000 [ 60%]  (Sampling) (Chain 1)
Iteration: 700 / 1000 [ 70%]  (Sampling) (Chain 0)
Iteration: 600 / 1000 [ 60%]  (Sampling) (Chain 2)
Iteration: 600 / 1000 [ 60%]  (Sampling) (Chain 3)
Iteration: 700 / 1000 [ 70%]  (Sampling) (Chain 2)
Iteration: 700 / 1000 [ 70%]  (Sampling) (Chain 1)
Iteration: 800 / 1000 [ 80%]  (Sampling) (Chain 0)
Iteration: 800 / 1000 [ 80%]  (Sampling) (Chain 2)
Iteration: 700 / 1000 [ 70%]  (Sampling) (Chain 3)
Iteration: 800 / 1000 [ 80%]  (Sampling) (Chain 1)
Iteration: 900 / 1000 [ 90%]  (Sampling) (Chain 0)
Iteration: 900 / 1000 [ 90%]  (Sampling) (Chain 2)
Iteration: 1000 / 1000 [100%]  (Sampling) (Chain 2)
# 
#  Elapsed Time: 0.019416 seconds (Warm-up)
#                0.011221 seconds (Sampling)
#                0.030637 seconds (Total)
# 
Iteration: 1000 / 1000 [100%]  (Sampling) (Chain 0)
Iteration: 800 / 1000 [ 80%]  (Sampling) (Chain 3)
# 
#  Elapsed Time: 0.016078 seconds (Warm-up)
#                0.014859 seconds (Sampling)
#                0.030937 seconds (Total)
# 
Iteration: 900 / 1000 [ 90%]  (Sampling) (Chain 1)
Iteration: 900 / 1000 [ 90%]  (Sampling) (Chain 3)
Iteration: 1000 / 1000 [100%]  (Sampling) (Chain 1)
# 
#  Elapsed Time: 0.017019 seconds (Warm-up)
#                0.018034 seconds (Sampling)
#                0.035053 seconds (Total)
# 
Iteration: 1000 / 1000 [100%]  (Sampling) (Chain 3)
# 
#  Elapsed Time: 0.019982 seconds (Warm-up)
#                0.017261 seconds (Sampling)
#                0.037243 seconds (Total)
# 
```

#### PyStan Version:

2.15.0.0

#### Python Version:

2.7.13

#### Operating System:

Linux x86_64 4.9.18

**Comment by ariddell** [comment]
Thanks for the report and the steps to reproduce.

- Works fine with Python 3.5 for me.
- and I get the same error on Python 2.

**Comment by ariddell** [comment]
Apparently there's a lingering bug mentioned at the bottom of #249. Fix is here: https://stackoverflow.com/questions/25968518/python-multiprocessing-lib-error-attributeerror-exit

I'll change this and make a 2.15.0.1 release.

**Comment by monga** [comment]
Yes, your diagnosis looks right. Thank you!
