### ISSUE TITLE
Install fails on M1 Apple Silicon

### ISSUE THREAD

**Issue by vlsd** [stan-dev/pystan#335]
#### Describe the bug
Install fails on M1 Apple. Trying to install errors out when clag tries to compile `pystan/_misc.cpp`

#### Describe your system

macOS Monterey 12.1
Apple M1 Pro (arm64)
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin21.2.0
Python 3.10.0 installed through pyenv

#### Steps/Code to Reproduce
Try to install through pip
```
pip install pystan
```

#### Error
```
    building 'pystan._misc' extension
    C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include
    
    compile options: '-I/Users/vlsd/.pyenv/versions/3.10.0/include/python3.10 -c'
    extra options: '-Os -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized -std=c++1y'
    clang: pystan/_misc.cpp
    pystan/_misc.cpp:15723:5: error: expression is not assignable
        ++Py_REFCNT(o);
        ^ ~~~~~~~~~~~~
    pystan/_misc.cpp:15725:5: error: expression is not assignable
        --Py_REFCNT(o);
        ^ ~~~~~~~~~~~~
    pystan/_misc.cpp:16018:5: error: expression is not assignable
        ++Py_REFCNT(o);
        ^ ~~~~~~~~~~~~
    pystan/_misc.cpp:16020:5: error: expression is not assignable
        --Py_REFCNT(o);
        ^ ~~~~~~~~~~~~
    pystan/_misc.cpp:16260:5: error: expression is not assignable
        ++Py_REFCNT(o);
        ^ ~~~~~~~~~~~~
    pystan/_misc.cpp:16262:5: error: expression is not assignable
        --Py_REFCNT(o);
        ^ ~~~~~~~~~~~~
```

The full error is in this gist https://gist.github.com/vlsd/3961ce239ec1ec1c001e470a8b688ace

**Comment by ahartikainen** [comment]
That is weird. It tries to install 2.x

I recommend that you compile the wheel for httpstan + pystan manually and install them from the wheels.

https://httpstan.readthedocs.io/en/latest/installation.html

**Comment by vlsd** [comment]
@ahartikainen that makes a lot of sense, because I'm ultimately trying to install fbprophet, which, from what I can tell, depends on pystan 2.x

out of curiosity, how were you able to tell that this tried to install 2.x?

**Comment by ahartikainen** [comment]
Those files are not present in pystan 3.

Could you use CmdStanPy interface for prophet?

**Comment by sedulam** [comment]
@ahartikainen I'm having the same issue

Following the steps on https://httpstan.readthedocs.io/en/latest/installation.html, what should be the arguments for `make` in the "Build shared libraries and generate code" step?

**Comment by ahartikainen** [comment]
No arguments

**Comment by sedulam** [comment]
Running "make" without arguments, it complains from the lack of targets. Full output below:
```
(venv3-10) gordo@pedros-mbp bin % /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/bin/python -m pip install poetry
make
Collecting poetry
  Using cached poetry-1.1.12-py2.py3-none-any.whl (175 kB)
Collecting packaging<21.0,>=20.4
  Using cached packaging-20.9-py2.py3-none-any.whl (40 kB)
Collecting pkginfo<2.0,>=1.4
  Using cached pkginfo-1.8.2-py2.py3-none-any.whl (26 kB)
Collecting tomlkit<1.0.0,>=0.7.0
  Using cached tomlkit-0.8.0-py3-none-any.whl (33 kB)
Collecting pexpect<5.0.0,>=4.7.0
  Using cached pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting poetry-core<1.1.0,>=1.0.7
  Using cached poetry_core-1.0.7-py2.py3-none-any.whl (424 kB)
Collecting cleo<0.9.0,>=0.8.1
  Using cached cleo-0.8.1-py2.py3-none-any.whl (21 kB)
Collecting keyring<22.0.0,>=21.2.0
  Using cached keyring-21.8.0-py3-none-any.whl (32 kB)
Collecting clikit<0.7.0,>=0.6.2
  Using cached clikit-0.6.2-py2.py3-none-any.whl (91 kB)
Collecting requests-toolbelt<0.10.0,>=0.9.1
  Using cached requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
Collecting cachecontrol[filecache]<0.13.0,>=0.12.9
  Using cached CacheControl-0.12.10-py2.py3-none-any.whl (20 kB)
Collecting crashtest<0.4.0,>=0.3.0
  Using cached crashtest-0.3.1-py3-none-any.whl (7.0 kB)
Collecting html5lib<2.0,>=1.0
  Using cached html5lib-1.1-py2.py3-none-any.whl (112 kB)
Collecting cachy<0.4.0,>=0.3.0
  Using cached cachy-0.3.0-py2.py3-none-any.whl (20 kB)
Collecting requests<3.0,>=2.18
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting virtualenv<21.0.0,>=20.0.26
  Downloading virtualenv-20.12.0-py2.py3-none-any.whl (6.5 MB)
     |████████████████████████████████| 6.5 MB 2.4 MB/s
Collecting shellingham<2.0,>=1.1
  Using cached shellingham-1.4.0-py2.py3-none-any.whl (9.4 kB)
Collecting msgpack>=0.5.2
  Using cached msgpack-1.0.3-cp310-cp310-macosx_10_9_universal2.whl (130 kB)
Collecting lockfile>=0.9
  Using cached lockfile-0.12.2-py2.py3-none-any.whl (13 kB)
Collecting pylev<2.0,>=1.3
  Using cached pylev-1.4.0-py2.py3-none-any.whl (6.1 kB)
Collecting pastel<0.3.0,>=0.2.0
  Using cached pastel-0.2.1-py2.py3-none-any.whl (6.0 kB)
Collecting webencodings
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: six>=1.9 in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from html5lib<2.0,>=1.0->poetry) (1.16.0)
Requirement already satisfied: pyparsing>=2.0.2 in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from packaging<21.0,>=20.4->poetry) (3.0.6)
Collecting ptyprocess>=0.5
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.9-py3-none-any.whl (39 kB)
Collecting platformdirs<3,>=2
  Using cached platformdirs-2.4.1-py3-none-any.whl (14 kB)
Collecting distlib<1,>=0.3.1
  Using cached distlib-0.3.4-py2.py3-none-any.whl (461 kB)
Collecting filelock<4,>=3.2
  Using cached filelock-3.4.2-py3-none-any.whl (9.9 kB)
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests, pylev, pastel, msgpack, crashtest, webencodings, ptyprocess, platformdirs, lockfile, filelock, distlib, clikit, cachecontrol, virtualenv, tomlkit, shellingham, requests-toolbelt, poetry-core, pkginfo, pexpect, packaging, keyring, html5lib, cleo, cachy, poetry
  Attempting uninstall: packaging
    Found existing installation: packaging 21.3
    Uninstalling packaging-21.3:
      Successfully uninstalled packaging-21.3
Successfully installed cachecontrol-0.12.10 cachy-0.3.0 certifi-2021.10.8 charset-normalizer-2.0.9 cleo-0.8.1 clikit-0.6.2 crashtest-0.3.1 distlib-0.3.4 filelock-3.4.2 html5lib-1.1 idna-3.3 keyring-21.8.0 lockfile-0.12.2 msgpack-1.0.3 packaging-20.9 pastel-0.2.1 pexpect-4.8.0 pkginfo-1.8.2 platformdirs-2.4.1 poetry-1.1.12 poetry-core-1.0.7 ptyprocess-0.7.0 pylev-1.4.0 requests-2.26.0 requests-toolbelt-0.9.1 shellingham-1.4.0 tomlkit-0.8.0 urllib3-1.26.7 virtualenv-20.12.0 webencodings-0.5.1
WARNING: You are using pip version 21.1.2; however, version 21.3.1 is available.
You should consider upgrading via the '/Users/gordo/PycharmProjects/old-hc-generator/venv3-10/bin/python -m pip install --upgrade pip' command.
make: *** No targets specified and no makefile found.  Stop
```

**Comment by sedulam** [comment]
I was able to install it from the source but it seems to be ignoring the installed package and going for pystan 2.19.1.1:
```
(venv3-10) gordo@pedros-mbp stan-dev % /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/bin/python -m pip show httpstan
Name: httpstan
Version: 4.6.1
Summary: HTTP-based interface to Stan, a package for Bayesian inference.
Home-page: https://mc-stan.org
Author: Allen Riddell
Author-email: riddella@indiana.edu
License: ISC
Location: /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages
Requires: aiohttp, appdirs, marshmallow, numpy, setuptools, webargs
Required-by: pystan
(venv3-10) gordo@pedros-mbp stan-dev % /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/bin/python -m pip show pystan
Name: pystan
Version: 3.3.0
Summary: Python interface to Stan, a package for Bayesian inference
Home-page: https://mc-stan.org
Author: Allen Riddell
Author-email: riddella@indiana.edu
License: ISC
Location: /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages
Requires: aiohttp, clikit, httpstan, numpy, pysimdjson
Required-by:
```

However, when I try to install Prophet, it still errors out:
```
(venv3-10) gordo@pedros-mbp stan-dev % source /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/bin/activate
pip install prophet~=1.0.1 > ~/prophet-install.log
  ERROR: Command errored out with exit status 1:
   command: /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/x1/x6y1719j0wl6f1_7j9qmnl3r0000gn/T/pip-install-zwwxgbxy/prophet_460f90c4e00a4d9fbf8481921b0df434/setup.py'"'"'; __file__='"'"'/private/var/folders/x1/x6y1719j0wl6f1_7j9qmnl3r0000gn/T/pip-install-zwwxgbxy/prophet_460f90c4e00a4d9fbf8481921b0df434/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/x1/x6y1719j0wl6f1_7j9qmnl3r0000gn/T/pip-wheel-gwz3sq1t
       cwd: /private/var/folders/x1/x6y1719j0wl6f1_7j9qmnl3r0000gn/T/pip-install-zwwxgbxy/prophet_460f90c4e00a4d9fbf8481921b0df434/
  Complete output (38 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/prophet
  creating build/lib/prophet/stan_model
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/x1/x6y1719j0wl6f1_7j9qmnl3r0000gn/T/pip-install-zwwxgbxy/prophet_460f90c4e00a4d9fbf8481921b0df434/setup.py", line 123, in <module>
      setup(
    File "/Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/x1/x6y1719j0wl6f1_7j9qmnl3r0000gn/T/pip-install-zwwxgbxy/prophet_460f90c4e00a4d9fbf8481921b0df434/setup.py", line 48, in run
      build_models(target_dir)
    File "/private/var/folders/x1/x6y1719j0wl6f1_7j9qmnl3r0000gn/T/pip-install-zwwxgbxy/prophet_460f90c4e00a4d9fbf8481921b0df434/setup.py", line 38, in build_models
      StanBackendEnum.get_backend_class(backend).build_model(target_dir, MODEL_DIR)
    File "/private/var/folders/x1/x6y1719j0wl6f1_7j9qmnl3r0000gn/T/pip-install-zwwxgbxy/prophet_460f90c4e00a4d9fbf8481921b0df434/prophet/models.py", line 228, in build_model
      import pystan
  ModuleNotFoundError: No module named 'pystan'
  ----------------------------------------
  ERROR: Failed building wheel for prophet
```
It produced the following log:
```
Collecting prophet~=1.0.1
  Using cached prophet-1.0.1.tar.gz (65 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: Cython>=0.22 in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from prophet~=1.0.1) (0.29.26)
Collecting cmdstanpy==0.9.68
  Using cached cmdstanpy-0.9.68-py3-none-any.whl (49 kB)
Collecting pystan~=2.19.1.1
  Using cached pystan-2.19.1.1.tar.gz (16.2 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: numpy>=1.15.4 in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from prophet~=1.0.1) (1.21.5)
Requirement already satisfied: pandas>=1.0.4 in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from prophet~=1.0.1) (1.3.5)
Requirement already satisfied: matplotlib>=2.0.0 in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from prophet~=1.0.1) (3.5.1)
Requirement already satisfied: LunarCalendar>=0.0.9 in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from prophet~=1.0.1) (0.0.9)
Requirement already satisfied: convertdate>=2.1.2 in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from prophet~=1.0.1) (2.3.2)
Requirement already satisfied: holidays>=0.10.2 in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from prophet~=1.0.1) (0.11.3.1)
Requirement already satisfied: setuptools-git>=1.2 in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from prophet~=1.0.1) (1.2)
Requirement already satisfied: python-dateutil>=2.8.0 in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from prophet~=1.0.1) (2.8.2)
Requirement already satisfied: tqdm>=4.36.1 in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from prophet~=1.0.1) (4.62.3)
Requirement already satisfied: ujson in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from cmdstanpy==0.9.68->prophet~=1.0.1) (5.1.0)
Requirement already satisfied: pymeeus<=1,>=0.3.13 in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from convertdate>=2.1.2->prophet~=1.0.1) (0.5.11)
Requirement already satisfied: pytz>=2014.10 in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from convertdate>=2.1.2->prophet~=1.0.1) (2021.3)
Requirement already satisfied: hijri-converter in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from holidays>=0.10.2->prophet~=1.0.1) (2.2.2)
Requirement already satisfied: korean-lunar-calendar in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from holidays>=0.10.2->prophet~=1.0.1) (0.2.1)
Requirement already satisfied: ephem>=3.7.5.3 in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from LunarCalendar>=0.0.9->prophet~=1.0.1) (4.1.3)
Requirement already satisfied: fonttools>=4.22.0 in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from matplotlib>=2.0.0->prophet~=1.0.1) (4.28.5)
Requirement already satisfied: pillow>=6.2.0 in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from matplotlib>=2.0.0->prophet~=1.0.1) (8.4.0)
Requirement already satisfied: cycler>=0.10 in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from matplotlib>=2.0.0->prophet~=1.0.1) (0.11.0)
Requirement already satisfied: packaging>=20.0 in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from matplotlib>=2.0.0->prophet~=1.0.1) (20.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from matplotlib>=2.0.0->prophet~=1.0.1) (1.3.2)
Requirement already satisfied: pyparsing>=2.2.1 in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from matplotlib>=2.0.0->prophet~=1.0.1) (3.0.6)
Requirement already satisfied: six>=1.5 in /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages (from python-dateutil>=2.8.0->prophet~=1.0.1) (1.16.0)
Building wheels for collected packages: prophet, pystan
  Building wheel for prophet (setup.py): started
  Building wheel for prophet (setup.py): finished with status 'error'
  Running setup.py clean for prophet
  Building wheel for pystan (setup.py): started
  Building wheel for pystan (setup.py): still running...
  Building wheel for pystan (setup.py): finished with status 'error'
  Running setup.py clean for pystan
Failed to build prophet pystan
Installing collected packages: pystan, cmdstanpy, prophet
  Attempting uninstall: pystan
    Found existing installation: pystan 3.3.0
    Uninstalling pystan-3.3.0:
      Successfully uninstalled pystan-3.3.0
    Running setup.py install for pystan: started
    Running setup.py install for pystan: finished with status 'error'
  Rolling back uninstall of pystan
  Moving to /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages/pystan-3.3.0.dist-info/
   from /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages/~ystan-3.3.0.dist-info
  Moving to /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages/stan/
   from /Users/gordo/PycharmProjects/old-hc-generator/venv3-10/lib/python3.10/site-packages/~tan

```

**Comment by ahartikainen** [comment]
Prophet does not work with pystan 3.x

I recommend using CmdStanPy

**Comment by vlsd** [comment]
> I recommend using CmdStanPy

I haven't gotten around to trying that, because I managed to install and use 2.x under emulation, but I will try in the future. 

Knowing that I was in fact trying to install 2.x rather than 3.x was key. I think We can mark this issue as solved, and put it under "user error"
