### ISSUE TITLE
If the sampling results are all the same value, plotting can not be done

### ISSUE THREAD

**Issue by TaskeHAMANO** [stan-dev/pystan#339]
#### Description:

fit.plot returns an error if the sampled values are all the same value.
This is due to pymc's plot.py doing kernel density estimation.

##### My opinion
pymc's plot.py outputs a histogram without estimating the kernel density if the given data type is int type.
However, sampling values obtained with pystan are all in float type. This is because it is using cython.
Therefore, I think that it is appropriate to change the implementation so that the dictionary type can be passed to the plot function.

#### Reproducible Steps:

```python
import numpy as np
import os
import pystan
import pickle
import matplotlib.pyplot as plt


a = np.array([56,55,55,62,54,63,47,58,56,56,57,52,53,50,50,57,57,55,60,65,53,43,60,51,52,
60,54,49,56,54,55,57,53,58,54,57,60,57,53,61,60,58,56,52,62,52,66,63,54,50])
b = np.array([33,37,59,41,42,61,46,25,32,35,55,44,45,41,33,61,46,16,48,34,27,37,28,31,32,
20,50,42,26,55,45,36,51,51,50,48,47,39,36,35,32,38,25,66,54,27,35,34,49,39])

stan_file = os.path.join("stan", "g2_ind.stan")
stan_file_c = os.path.join("stan", "g2_ind.pkl")
model = pystan.StanModel(file=stan_file)
with open(stan_file_c, "wb") as f:
    pickle.dump(model, f)

stan_data = {"n_a": a.size,
             "n_b": b.size,
             "a": a,
             "b": b}

par = ["mu_a",
       "sigma_a",
       "mu_b",
       "sigma_b",
       "mu_diff",
       "prob_mu_diff_upper_0"]
prob = [0.025, 0.05, 0.25, 0.5, 0.75, 0.95, 0.975]

stan_file_c = os.path.join("stan", "g2_ind.pkl")
with open(stan_file_c, "rb") as f:
    model = pickle.load(f)

fit = model.sampling(data=stan_data,
                     pars=par,
                     iter=21000,
                     chains=5,
                     warmup=1000,
                     seed=1234,
                     algorithm="NUTS")

fit.plot(par)
```

g2_ind.stan
```stan
data {
    int<lower=0> n_a ;
    int<lower=0> n_b ;
    real<lower=0> a[n_a] ;
    real<lower=0> b[n_b] ;
}

parameters {
    real<lower=0> mu_a ;
    real<lower=0> sigma_a ;
    real<lower=0> mu_b ;
    real<lower=0> sigma_b ;
}

model {
    a ~ normal(mu_a, sigma_a) ;
    b ~ normal(mu_b, sigma_b) ;
}

generated quantities {
    real mu_diff ;
    int<lower=0, upper=1> prob_mu_diff_upper_0 ;

    mu_diff = mu_a - mu_b ;
    prob_mu_diff_upper_0 = mu_diff > 0 ? 1 : 0 ;
}
```

#### Current Output:

```python
Traceback (most recent call last):
  File "test.py", line 51, in <module>
    fit.plot(par)
  File "stanfit4anon_model_8b9c3ea2e7d160af9f4d695f94cd1953_1817414347569073501.pyx", line 504, in stanfit4anon_model_8b9c3ea2e7d160af9f4d695f94cd1953_1817414347569073501.StanFit4Model.plot (/var/folders/s3/wv3h2hcd2c317rbnll_nzq6r0000gn/T/tmp2hlp0dc_/stanfit4anon_model_8b9c3ea2e7d160af9f4d695f94cd1953_1817414347569073501.cpp:10373)
  File "/usr/local/var/pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/pystan/plots.py", line 19, in traceplot
    return plots.traceplot(fit.extract(), pars, **kwargs)
  File "/usr/local/var/pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/pystan/external/pymc/plots.py", line 41, in traceplot
    kdeplot_op(ax[i, 0], d)
  File "/usr/local/var/pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/pystan/external/pymc/plots.py", line 55, in kdeplot_op
    density = kde.gaussian_kde(d)
  File "/usr/local/var/pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/scipy/stats/kde.py", line 172, in __init__
    self.set_bandwidth(bw_method=bw_method)
  File "/usr/local/var/pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/scipy/stats/kde.py", line 499, in set_bandwidth
    self._compute_covariance()
  File "/usr/local/var/pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/scipy/stats/kde.py", line 510, in _compute_covariance
    self._data_inv_cov = linalg.inv(self._data_covariance)
  File "/usr/local/var/pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/scipy/linalg/basic.py", line 819, in inv
    raise LinAlgError("singular matrix")
numpy.linalg.linalg.LinAlgError: singular matrix
```

#### Expected Output:

Visualized plot without error.

#### PyStan Version:

2.15.0.1

#### Python Version:

3.5.1 with anaconda

#### Operating System:

OSX 10.11.6

**Comment by ahartikainen** [comment]
Hi,

there are plans to use new plotting library mcmcplotlib. It is still in the early stage.

see
- https://github.com/mcmcplotlib/mcmcplotlib
- https://github.com/stan-dev/pystan/issues/315

In the mean time, we could update our plotting utilities to read also dictionary (and use the new kde plot). Any opinions on that?

I'm not sure if the integer / floating point conversion is due to Cython or Stan C++ library.

**Comment by ariddell** [comment]
This looks like a bug in the (likely out-of-date) pymc code used for plotting. Perhaps there's a newer version that fixes the bug?

**Comment by ahartikainen** [comment]
I believe the ArviZ library has fixed this problem. We can close this PR after we have moved plotting to ArviZ.

**Comment by ahartikainen** [comment]
Closing due to inactivity. Can be reopened if needed.
