### ISSUE TITLE
Something went wrong while unpickling the StanModel

### ISSUE THREAD

**Issue by Ram0987** [stan-dev/pystan#366]
I have installed both pystan and fbprophet successfully on my machine. But, When I give `import fbprophet`, It is showing an error: 

`WARNING:pystan:No module named 'stanfit4anon_model_9c941523472e65f75f241e35a8769919_4289282227191412751'
WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.`

`WARNING:pystan:No module named 'stanfit4anon_model_77e4c4162fb17d5855e6b726b68bdd0c_4498328616688083170'
WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.`

I'm using:
#### Operating System: Windows 10

Please explain how to fix this. Thanks!

**Comment by ahartikainen** [comment]
This is probably a problem with `fbprophet`. It's probably using some precompiled model that it tries to import.

PyStan transforms Stan code to C++ that is compiled to Python module with Cython. That module is then imported to Python as any normal module. Normally this is done under the hood, so usually users don't need to import anything explicitly.

**Comment by Ram0987** [comment]
@ahartikainen Thanks for the reply!

`import pystan`
`model_code = 'parameters {real y;} model {y ~ normal(0,1);}'`
`model = pystan.StanModel(model_code=model_code)`
`y = model.sampling(n_jobs=1).extract()['y']`
`y.mean()`

When I  run this code, it says:

Generating code
Finished generating code
LINK : fatal error LNK1158: cannot run 'rc.exe'
Traceback (most recent call last):
  File "C:\Python3.6.1\lib\distutils\_msvccompiler.py", line 478, in link
    self.spawn([self.linker] + ld_args)
  File "C:\Python3.6.1\lib\distutils\_msvccompiler.py", line 501, in spawn
    return super().spawn(cmd)
  File "C:\Python3.6.1\lib\distutils\ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "C:\Python3.6.1\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:\Python3.6.1\lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\link.exe' failed with exit status 1158

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python3.6.1\lib\site-packages\pystan\model.py", line 311, in __init__
    build_extension.run()
  File "C:\Python3.6.1\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Python3.6.1\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "C:\Python3.6.1\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Python3.6.1\lib\distutils\command\build_ext.py", line 558, in build_extension
    target_lang=language)
  File "C:\Python3.6.1\lib\distutils\ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "C:\Python3.6.1\lib\distutils\_msvccompiler.py", line 481, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\link.exe' failed with exit status 1158


I don't know the reason . could you help me fix this problem? thanks a lot!

**Comment by ahartikainen** [comment]
Have you followed the instructions for installing compiler with SDK 8 and 10 (please use 14.0 / msvc 2015)

https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.0_standalone:_Visual_C.2B-.2B-_Build_Tools_2015_.28x86.2C_x64.2C_ARM.29

**Comment by Ram0987** [comment]
Thank you very much for the response. Actually, I didn't install SDK 8 before.
Thank again 👍
