### ISSUE TITLE
Eight Schools example: command 'gcc' failed with exit status 4

### ISSUE THREAD

**Issue by mrclttnz** [stan-dev/pystan#489]
#### Summary:
I have just installed pytstan (using `pip3 install pystan==2.17.0.0`) and I'm trying to run the first "Eight Schools" example.  
I get a `distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 4` error

#### Description:
I am trying to run the first pystan example to see if the installation was successful. I've got the code from [here](https://pystan.readthedocs.io/en/latest/getting_started.html#example-1-eight-schools) and have run it in a python 3.6 session  
What am I doing wrong? Or is there anything missing in my setup?

#### Reproducible Steps:
Opened a fresh python3 session, imported pystan and submitted the code at https://pystan.readthedocs.io/en/latest/getting_started.html#example-1-eight-schools

#### Current Output:
```
Python 3.6.3 (default, Jan  4 2018, 16:40:53)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pystan
>>>
>>>
>>> schools_code = """
... data {
...     int<lower=0> J; // number of schools
...     real y[J]; // estimated treatment effects
...     real<lower=0> sigma[J]; // s.e. of effect estimates
... }
... parameters {
...     real mu;
...     real<lower=0> tau;
...     real eta[J];
... }
... transformed parameters {
...     real theta[J];
...     for (j in 1:J)
...     theta[j] = mu + tau * eta[j];
... }
... model {
...     eta ~ normal(0, 1);
...     y ~ normal(theta, sigma);
... }
... """
>>>
>>> schools_dat = {'J': 8,
...                'y': [28,  8, -3,  7, -1,  1, 18, 12],
...                'sigma': [15, 10, 16, 11,  9, 11, 10, 18]}
>>>
>>> sm = pystan.StanModel(model_code=schools_code)
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_cbe9cd2f1e5ab5d1c7cce1f23ca970b4 NOW.
Traceback (most recent call last):
  File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 127, in _compile
    extra_postargs)
  File "/usr/lib64/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib64/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib64/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/pystan/model.py", line 313, in __init__
    build_extension.run()
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/usr/lib64/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 129, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 4
>>>
```

#### Expected Output:
Whatever the example should provide as output

#### PyStan Version:
2.17.0.0

#### Python Version:
3.6.3

#### Operating System:
CentOS Linux release 7.5.1804

**Comment by ahartikainen** [comment]
Hi, 

what is your gcc version?

**Comment by ahartikainen** [comment]
How much of RAM do you have? It could be running out of free memory.

**Comment by mrclttnz** [comment]
Hi @ahartikainen 

here's the info requested

```
#> gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC)
```

This is currently running in a VM with 13 GB free. Is this enough for the example?

Thanks for looking into it!

**Comment by mrclttnz** [comment]
And this is the output with `verbose=True`
```
>>> sm = pystan.StanModel(model_code=schools_code, verbose=True)
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_cbe9cd2f1e5ab5d1c7cce1f23ca970b4 NOW.
INFO:pystan:OS: linux, Python: 3.6.3 (default, Jan  4 2018, 16:40:53)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)], Cython 0.28.2
Compiling /tmp/tmp3e8o_h_m/stanfit4anon_model_cbe9cd2f1e5ab5d1c7cce1f23ca970b4_6170262873262085706.pyx because                                                                  it changed.
[1/1] Cythonizing /tmp/tmp3e8o_h_m/stanfit4anon_model_cbe9cd2f1e5ab5d1c7cce1f23ca970b4_6170262873262085706.pyx
building 'stanfit4anon_model_cbe9cd2f1e5ab5d1c7cce1f23ca970b4_6170262873262085706' extension
creating /tmp/tmp3e8o_h_m/tmp
creating /tmp/tmp3e8o_h_m/tmp/tmp3e8o_h_m
gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,                                                                 -D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64                                                                  -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_                                                                 ASSERTS -Itmp/tmp3e8o_h_m -Iusr/local/lib64/python3.6/site-packages/pystan -I/tmp/tmp3e8o_h_m -I/usr/local/lib6                                                                 4/python3.6/site-packages/pystan -I/usr/local/lib64/python3.6/site-packages/pystan/stan/src -I/usr/local/lib64/                                                                 python3.6/site-packages/pystan/stan/lib/stan_math -I/usr/local/lib64/python3.6/site-packages/pystan/stan/lib/st                                                                 an_math/lib/eigen_3.3.3 -I/usr/local/lib64/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.64.0 -                                                                 I/usr/local/lib64/python3.6/site-packages/pystan/stan/lib/stan_math/lib/cvodes_2.9.0/include -I/usr/local/lib64                                                                 /python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c /tmp/tmp3e8o_h_m/stanfit4anon_model_cb                                                                 e9cd2f1e5ab5d1c7cce1f23ca970b4_6170262873262085706.cpp -o /tmp/tmp3e8o_h_m/tmp/tmp3e8o_h_m/stanfit4anon_model_c                                                                 be9cd2f1e5ab5d1c7cce1f23ca970b4_6170262873262085706.o -O2 -ftemplate-depth-256 -Wno-unused-function -Wno-uninit                                                                 ialized
In file included from /usr/local/lib64/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                 from /usr/local/lib64/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/local/lib64/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /tmp/tmp3e8o_h_m/stanfit4anon_model_cbe9cd2f1e5ab5d1c7cce1f23ca970b4_6170262873262085706.                                                                 cpp:642:
/usr/local/lib64/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warn                                                                 ing "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from /usr/local/lib64/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.64.0/boost                                                                 /multi_array/base.hpp:28:0,
ib64/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.64.0 -I/usr/local/lib64/python3.6/site-packages/pystan/stan/lib/stan_math/lib/cvodes_2.9.0/include -I/usr/local/lib64/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c /tmp/tmp3e8o_h_m/stanfit4anon_model_cbe9cd2f1e5ab5d1c7cce1f23ca970b4_6170262873262085706.cpp -o /tmp/tmp3e8o_h_m/tmp/tmp3e8o_h_m/stanfit4anon_model_cbe9cd2f1e5ab5d1c7cce1f23ca970b4_6170262873262085706.o -O2 -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized
In file included from /usr/local/lib64/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                 from /usr/local/lib64/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/local/lib64/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /tmp/tmp3e8o_h_m/stanfit4anon_model_cbe9cd2f1e5ab5d1c7cce1f23ca970b4_6170262873262085706.cpp:642:
/usr/local/lib64/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from /usr/local/lib64/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.64.0/boost/multi_array/base.hpp:28:0,
                 from /usr/local/lib64/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.64.0/boost/multi_array.hpp:21,
                 from /usr/local/lib64/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.64.0/boost/numeric/odeint/util/multi_array_adaption.hpp:29,
                 from /usr/local/lib64/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.64.0/boost/numeric/odeint.hpp:61,
                 from /usr/local/lib64/python3.6/site-packages/pystan/stan/lib/stan_math/stan/math/prim/arr/functor/integrate_ode_rk45.hpp:17,
                 from /usr/local/lib64/python3.6/site-packages/pystan/stan/lib/stan_math/stan/math/prim/arr.hpp:38,
                 from /usr/local/lib64/python3.6/site-packages/pystan/stan/lib/stan_math/stan/math/prim/mat.hpp:298,
                 from /usr/local/lib64/python3.6/site-packages/pystan/stan/lib/stan_math/stan/math/rev/mat.hpp:12,
                 from /usr/local/lib64/python3.6/site-packages/pystan/stan/src/stan/model/log_prob_grad.hpp:4,
                 from /usr/local/lib64/python3.6/site-packages/pystan/stan/src/stan/model/test_gradients.hpp:7,
                 from /usr/local/lib64/python3.6/site-packages/pystan/stan/src/stan/services/diagnose/diagnose.hpp:10,
                 from usr/local/lib64/python3.6/site-packages/pystan/stan_fit.hpp:22,
                 from /tmp/tmp3e8o_h_m/stanfit4anon_model_cbe9cd2f1e5ab5d1c7cce1f23ca970b4_6170262873262085706.cpp:646:
/usr/local/lib64/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.64.0/boost/multi_array/concept_checks.hpp: In static member function ‘static void boost::multi_array_concepts::detail::idgen_helper<N>::call(Array&, const IdxGen&, Call_Type)’:
/usr/local/lib64/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.64.0/boost/multi_array/concept_checks.hpp:42:43: warning: typedef ‘index_range’ locally defined but not used [-Wunused-local-typedefs]
       typedef typename Array::index_range index_range;
                                           ^
/usr/local/lib64/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.64.0/boost/multi_array/concept_checks.hpp:43:37: warning: typedef ‘index’ locally defined but not used [-Wunused-local-typedefs]
       typedef typename Array::index index;
                                     ^
/usr/local/lib64/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.64.0/boost/multi_array/concept_checks.hpp: In static member function ‘static void boost::multi_array_concepts::detail::idgen_helper<0ul>::call(Array&, const IdxGen&, Call_Type)’:
/usr/local/lib64/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.64.0/boost/multi_array/concept_checks.hpp:53:43: warning: typedef ‘index_range’ locally defined but not used [-Wunused-local-typedefs]
       typedef typename Array::index_range index_range;
                                           ^
/usr/local/lib64/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.64.0/boost/multi_array/concept_checks.hpp:54:37: warning: typedef ‘index’ locally defined but not used [-Wunused-local-typedefs]
       typedef typename Array::index index;
                                     ^
/tmp/tmp3e8o_h_m/stanfit4anon_model_cbe9cd2f1e5ab5d1c7cce1f23ca970b4_6170262873262085706.cpp: In function ‘PyObject* __pyx_pf_71stanfit4anon_model_cbe9cd2f1e5ab5d1c7cce1f23ca970b4_6170262873262085706_2_call_sampler(PyObject*, PyObject*, PyObject*, PyObject*)’:
/tmp/tmp3e8o_h_m/stanfit4anon_model_cbe9cd2f1e5ab5d1c7cce1f23ca970b4_6170262873262085706.cpp:9214:71: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     __pyx_t_12 = ((__pyx_t_9 != __pyx_v_fitptr->param_names_oi().size()) != 0);
                                                                       ^
{standard input}: Assembler messages:
{standard input}:208998: Warning: end of file not at end of a line; newline inserted
{standard input}:210807: Error: unknown pseudo-op: `.l'
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
Traceback (most recent call last):
  File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 127, in _compile
    extra_postargs)
  File "/usr/lib64/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib64/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib64/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/pystan/model.py", line 313, in __init__
    build_extension.run()
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/usr/lib64/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 129, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 4
>>>
```

**Comment by ahartikainen** [comment]
I don't think 4.8.5 is too old. 

13gb is more than enough to compile PyStan.

How did you install python?

Can you run your code with verbose so we can see what os failing (not sure will if it show anything new).

Also, is there any difference with n_jobs=1 and n_jobs=-1?

**Comment by mrclttnz** [comment]
python 3.6.3 is installed with `yum` from `epel` repo.

I've attached the log of the execution of the command `python3 -v test-pystan.py > test-pystan.log 2>&1`

[test-pystan.log](https://github.com/stan-dev/pystan/files/2258901/test-pystan.log)

**Comment by ahartikainen** [comment]
Hi, I totally missed your previous answer.

So the error is

```
{standard input}: Assembler messages:
{standard input}:208998: Warning: end of file not at end of a line; newline inserted
{standard input}:210807: Error: unknown pseudo-op: `.l'
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
gcc: internal compiler error: Killed (program cc1plus)
```

Based on google it still looks like a memory error.

Can you use htop to follow your memory usage?

Can you update your gcc?

**Comment by mrclttnz** [comment]
@ahartikainen I've made some further tests. I've upgraded `gcc` to version 7 but I am still getting the same error.  
I've also monitored memory and CPU usage by the `cc1plus` process: CPU never went above 40% and memory was never more than 9%.   

My next step is to create a fresh new CentOS 7 Docker container with python 3.6 and the same packages we have on the machine where it's failing. I'm basically removing some other system stuff we currently have in the Docker image we use. If the error still shows, I can then share the Docker image with you so it might be easier to debug what the error is

**Comment by mrclttnz** [comment]
@ahartikainen I have made some more tests and was able to run the code successfully. I think there was something wrong in the docker image we were using. While rebuilding the image we had to move from python 3.6.3 to 3.6.5 since the former was no longer available in the epel repo. Apparently this change has fixed the problem.
I am closing this issue. 
Thanks for your help!
