### ISSUE TITLE
Model not compiling with new threading support

### ISSUE THREAD

**Issue by hanyas** [stan-dev/pystan#500]
I'm tinkering with the pre-release code for pystan 2.18 in the develop branch and I am getting the following issues when I try to run the example code in #498. 

Looks like an issue with Stan-math and my gcc 5.4.0 (see compiler info below), still I thought i would share it here. Same setup works on different machine with gcc 8.2. Will try to update gcc and see if the errors disappear. Stan-math Wiki says it should work with gcc 4.9+.

When I remove the threading options it works fine.

The verbose output is huge and does not fit here, so I cut it down:

```INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_b06ba8857b9577a11f45439d5caaf32a NOW.
INFO:pystan:OS: linux, Python: 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:53:17) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)], Cython 0.28.5
Compiling /tmp/tmpp6c0qbbn/stanfit4anon_model_b06ba8857b9577a11f45439d5caaf32a_8761419117557555479.pyx because it changed.
[1/1] Cythonizing /tmp/tmpp6c0qbbn/stanfit4anon_model_b06ba8857b9577a11f45439d5caaf32a_8761419117557555479.pyx
building 'stanfit4anon_model_b06ba8857b9577a11f45439d5caaf32a_8761419117557555479' extension
creating /tmp/tmpp6c0qbbn/tmp
creating /tmp/tmpp6c0qbbn/tmp/tmpp6c0qbbn
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -m64 -fPIC -m64 -fPIC -fPIC -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -I/tmp/tmpp6c0qbbn -Iminiconda3/lib/python3.6/site-packages/pystan -I/home/abdulsamad/miniconda3/lib/python3.6/site-packages/pystan -I/home/abdulsamad/miniconda3/lib/python3.6/site-packages/pystan/stan/src -I/home/abdulsamad/miniconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math -I/home/abdulsamad/miniconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/lib/eigen_3.3.3 -I/home/abdulsamad/miniconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.66.0 -I/home/abdulsamad/miniconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/lib/sundials_3.1.0/include -I/home/abdulsamad/miniconda3/lib/python3.6/site-packages/numpy/core/include -I/home/abdulsamad/miniconda3/include/python3.6m -c /tmp/tmpp6c0qbbn/stanfit4anon_model_b06ba8857b9577a11f45439d5caaf32a_8761419117557555479.cpp -o /tmp/tmpp6c0qbbn/tmp/tmpp6c0qbbn/stanfit4anon_model_b06ba8857b9577a11f45439d5caaf32a_8761419117557555479.o -pthread -DSTAN_THREADS
In file included from /home/abdulsamad/miniconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                 from /home/abdulsamad/miniconda3/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/abdulsamad/miniconda3/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /tmp/tmpp6c0qbbn/stanfit4anon_model_b06ba8857b9577a11f45439d5caaf32a_8761419117557555479.cpp:640:
/home/abdulsamad/miniconda3/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from /home/abdulsamad/miniconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/stan/math/rev/core/gevv_vvv_vari.hpp:5:0,
                 from /home/abdulsamad/miniconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/stan/math/rev/core.hpp:12,
                 from /home/abdulsamad/miniconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/stan/math/rev/mat.hpp:4,
                 from /home/abdulsamad/miniconda3/lib/python3.6/site-packages/pystan/stan/src/stan/model/log_prob_grad.hpp:4,
                 from /home/abdulsamad/miniconda3/lib/python3.6/site-packages/pystan/stan/src/stan/model/test_gradients.hpp:7,
                 from /home/abdulsamad/miniconda3/lib/python3.6/site-packages/pystan/stan/src/stan/services/diagnose/diagnose.hpp:10,
                 from miniconda3/lib/python3.6/site-packages/pystan/stan_fit.hpp:22,
                 from /tmp/tmpp6c0qbbn/stanfit4anon_model_b06ba8857b9577a11f45439d5caaf32a_8761419117557555479.cpp:644:
/home/abdulsamad/miniconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/stan/math/rev/core/var.hpp:56:3: warning: identifier 'nullptr' is a keyword in C++11 [-Wc++0x-compat]
   bool is_uninitialized() { return (vi_ == static_cast<vari*>(nullptr)); }
   ^
In file included from /home/abdulsamad/miniconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/stan/math/prim/mat/fun/matrix_exp_multiply.hpp:5:0,
                 from /home/abdulsamad/miniconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/stan/math/prim/mat.hpp:162,
                 from /home/abdulsamad/miniconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/stan/math/rev/mat.hpp:12,
                 from /home/abdulsamad/miniconda3/lib/python3.6/site-packages/pystan/stan/src/stan/model/log_prob_grad.hpp:4,
                 from /home/abdulsamad/miniconda3/lib/python3.6/site-packages/pystan/stan/src/stan/model/test_gradients.hpp:7,
                 from /home/abdulsamad/miniconda3/lib/python3.6/site-packages/pystan/stan/src/stan/services/diagnose/diagnose.hpp:10,
                 from miniconda3/lib/python3.6/site-packages/pystan/stan_fit.hpp:22,
                 from /tmp/tmpp6c0qbbn/stanfit4anon_model_b06ba8857b9577a11f45439d5caaf32a_8761419117557555479.cpp:644:
/home/abdulsamad/miniconda3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/stan/math/prim/mat/fun/matrix_exp_action_handler.hpp:20:3: warning: identifier 'constexpr' is a keyword in C++11 [-Wc++0x-compat]
   static constexpr int p_max = 8;
   ^

Traceback (most recent call last):
  File "/home/abdulsamad/miniconda3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/abdulsamad/miniconda3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/abdulsamad/miniconda3/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/abdulsamad/miniconda3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pystan_threaded.py", line 65, in <module>
    extra_compile_args=extra_compile_args, verbose=True) 
  File "/home/abdulsamad/miniconda3/lib/python3.6/site-packages/pystan/model.py", line 340, in __init__
    build_extension.run()
  File "/home/abdulsamad/miniconda3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/abdulsamad/miniconda3/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/abdulsamad/miniconda3/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/abdulsamad/miniconda3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/abdulsamad/miniconda3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/abdulsamad/miniconda3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1
```

GCC version
```gcc -v       
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.10' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 
```

**Comment by hanyas** [comment]
Solved by pulling #499. I am guess it was the missing c++11 flags.
