### ISSUE TITLE
Readthedocs build failing

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan#503]
See https://readthedocs.org/projects/pystan/builds/7651074/

Looks like it's related to a new version of Sphinx.

```
Running Sphinx v1.7.6
loading translations [en]... done
WARNING: sphinx.ext.pngmath has been deprecated. Please use sphinx.ext.imgmath instead.

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pystan/envs/readthedocs/lib/python3.5/site-packages/sphinx/registry.py", line 315, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/pystan/checkouts/readthedocs/doc/sphinxext/numpydoc/__init__.py", line 3, in <module>
    from .numpydoc import setup
  File "/home/docs/checkouts/readthedocs.org/user_builds/pystan/checkouts/readthedocs/doc/sphinxext/numpydoc/numpydoc.py", line 29, in <module>
    from sphinx.util.compat import Directive
ImportError: cannot import name 'Directive'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pystan/envs/readthedocs/lib/python3.5/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pystan/envs/readthedocs/lib/python3.5/site-packages/sphinx/application.py", line 191, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pystan/envs/readthedocs/lib/python3.5/site-packages/sphinx/application.py", line 411, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pystan/envs/readthedocs/lib/python3.5/site-packages/sphinx/registry.py", line 318, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension numpydoc (exception: cannot import name 'Directive')

Extension error:
Could not import extension numpydoc (exception: cannot import name 'Directive')
```

**Comment by ahartikainen** [comment]
Is this still a problem?
