### ISSUE TITLE
Compile Error: 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by daeh** [stan-dev/pystan#550]
#### Summary:
I'm getting a gcc compilation error on include "ios"

#### Description:
I can compile models fine with cmdstan. I've tried all the steps suggested in https://github.com/stan-dev/pystan/issues/470 (installed gcc, `xcode-select --install`). My GCC version is 4.8.5. Strangely, it started out of nowhere (was working fine, then everything broke within the same interactive session).

#### Current Output:
```
Running code:: pystan.StanModel(file='ermodel__rand-slopes_group-cov_iaps-priors.stan', charset='utf-8', verbose=True)
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_bcbe7a28a65f7e3704431fd96ab7eeaa NOW.
INFO:pystan:OS: darwin, Python: 3.7.1 (default, Oct 23 2018, 14:07:42) 
[Clang 4.0.1 (tags/RELEASE_401/final)], Cython 0.29.2
Compiling /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpizfb9a2n/stanfit4anon_model_bcbe7a28a65f7e3704431fd96ab7eeaa_1490361736816663180.pyx because it changed.
[1/1] Cythonizing /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpizfb9a2n/stanfit4anon_model_bcbe7a28a65f7e3704431fd96ab7eeaa_1490361736816663180.pyx
building 'stanfit4anon_model_bcbe7a28a65f7e3704431fd96ab7eeaa_1490361736816663180' extension
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpizfb9a2n/var
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpizfb9a2n/var/folders
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpizfb9a2n/var/folders/x9
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpizfb9a2n/var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpizfb9a2n/var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpizfb9a2n/var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpizfb9a2n
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/daeda/anaconda3/envs/rpy/include -arch x86_64 -I/Users/daeda/anaconda3/envs/rpy/include -arch x86_64 -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -I/var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpizfb9a2n -I/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/pystan -I/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/pystan/stan/src -I/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/pystan/stan/lib/stan_math -I/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/pystan/stan/lib/stan_math/lib/eigen_3.3.3 -I/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/pystan/stan/lib/stan_math/lib/boost_1.66.0 -I/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/pystan/stan/lib/stan_math/lib/sundials_3.1.0/include -I/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/numpy/core/include -I/Users/daeda/anaconda3/envs/rpy/include/python3.7m -c /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpizfb9a2n/stanfit4anon_model_bcbe7a28a65f7e3704431fd96ab7eeaa_1490361736816663180.cpp -o /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpizfb9a2n/var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpizfb9a2n/stanfit4anon_model_bcbe7a28a65f7e3704431fd96ab7eeaa_1490361736816663180.o -O2 -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized -std=c++11
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
/var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpizfb9a2n/stanfit4anon_model_bcbe7a28a65f7e3704431fd96ab7eeaa_1490361736816663180.cpp:678:10: fatal error: 'ios' file not found
#include "ios"
         ^~~~~
1 warning and 1 error generated.
Traceback (most recent call last):
  File "/Users/daeda/anaconda3/envs/rpy/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/Users/daeda/anaconda3/envs/rpy/lib/python3.7/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/Users/daeda/anaconda3/envs/rpy/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/Users/daeda/anaconda3/envs/rpy/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-c052e13ac841>", line 40, in <module>
    sm, modelhash = runstan(model['modelpath'], model['name'], testcompile='yes')
  File "/Volumes/cristae/samadhi_daeda/coding/-GitRepos/adhder/analysis/behavioral/run_stanmodel.py", line 70, in runstan
    sm = compile_pycstan(modelpath, modelhash, modelname)
  File "/Volumes/cristae/samadhi_daeda/coding/-GitRepos/adhder/analysis/behavioral/run_stanmodel.py", line 46, in compile_pycstan
    sm = pystan.StanModel(file=str(modelpath), charset='utf-8', verbose=True)
  File "/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/pystan/model.py", line 349, in __init__
    build_extension.run()
  File "/Users/daeda/anaconda3/envs/rpy/lib/python3.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/Users/daeda/anaconda3/envs/rpy/lib/python3.7/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/Users/daeda/anaconda3/envs/rpy/lib/python3.7/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/Users/daeda/anaconda3/envs/rpy/lib/python3.7/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/Users/daeda/anaconda3/envs/rpy/lib/python3.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/Users/daeda/anaconda3/envs/rpy/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1
```

#### PyStan Version:
2.18.1.0

#### Python Version:
3.7.1

#### Operating System:
MacOS 10.14.2

**Comment by ahartikainen** [comment]
Hi, I think last longer comment has the answer https://github.com/pandas-dev/pandas/issues/23424 

So we need to update our codebase

https://github.com/pandas-dev/pandas/commit/459ebb2ad309938e9e68ae79e3bdb312efac0ca2

Can you call following lines before you build your model

    import os
 
   os.environ['MACOSX_DEPLOYMENT_TARGET'] = '10.9'

**Comment by daeh** [comment]
Thanks for the help. Setting the deployment target produces a numpy deprecation warning that seems to be terminating the compilation, which doesn't make any sense to me so maybe I'm just not reading the error correctly.

```
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_e66d773e298cf460136371fe888abe55 NOW.
INFO:pystan:OS: darwin, Python: 3.7.1 | packaged by conda-forge | (default, Nov 13 2018, 10:30:07) 
[Clang 4.0.1 (tags/RELEASE_401/final)], Cython 0.29.2
Compiling /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpze3mrox6/stanfit4anon_model_e66d773e298cf460136371fe888abe55_1762001848933651510.pyx because it changed.
[1/1] Cythonizing /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpze3mrox6/stanfit4anon_model_e66d773e298cf460136371fe888abe55_1762001848933651510.pyx
building 'stanfit4anon_model_e66d773e298cf460136371fe888abe55_1762001848933651510' extension
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpze3mrox6/var
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpze3mrox6/var/folders
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpze3mrox6/var/folders/x9
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpze3mrox6/var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpze3mrox6/var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpze3mrox6/var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpze3mrox6
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/daeda/anaconda3/envs/rpy/include -arch x86_64 -I/Users/daeda/anaconda3/envs/rpy/include -arch x86_64 -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -I/var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpze3mrox6 -I/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/pystan -I/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/pystan/stan/src -I/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/pystan/stan/lib/stan_math -I/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/pystan/stan/lib/stan_math/lib/eigen_3.3.3 -I/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/pystan/stan/lib/stan_math/lib/boost_1.66.0 -I/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/pystan/stan/lib/stan_math/lib/sundials_3.1.0/include -I/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/numpy/core/include -I/Users/daeda/anaconda3/envs/rpy/include/python3.7m -c /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpze3mrox6/stanfit4anon_model_e66d773e298cf460136371fe888abe55_1762001848933651510.cpp -o /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpze3mrox6/var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpze3mrox6/stanfit4anon_model_e66d773e298cf460136371fe888abe55_1762001848933651510.o -O2 -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized -std=c++11
In file included from /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpze3mrox6/stanfit4anon_model_e66d773e298cf460136371fe888abe55_1762001848933651510.cpp:688:
In file included from /Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
In file included from /Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1821:
/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it by " \
 ^
/var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmpze3mrox6/stanfit4anon_model_e66d773e298cf460136371fe888abe55_1762001848933651510.cpp:9314:30: warning: comparison of integers of different signs: 'Py_ssize_t' (aka 'long') and 'std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >::size_type' (aka 'unsigned long') [-Wsign-compare]
    __pyx_t_12 = ((__pyx_t_9 != __pyx_v_fitptr->param_names_oi().size()) != 0);
                   ~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by ahartikainen** [comment]
That is just a normal warning due to cython.

Can you try with numpy 1.15.x? Also on Python 3.6?

**Comment by daeh** [comment]
Still getting a gcc error with numpy 1.15.4 and python 3.6. I tried all the combinations of setting a development target and python 3.6/3.7 but it seems produce the same behavior.

```
Python 3.6.7 | packaged by conda-forge | (default, Nov 20 2018, 18:37:09)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import pystan
>>> import os
>>> import platform
>>> print(platform.system())
Darwin
>>> print(platform.release())
18.2.0
>>> print(pystan.__version__)
2.18.1.0
>>> print(np.__version__)
1.15.4
>>> os.environ['MACOSX_DEPLOYMENT_TARGET'] = '10.9'
>>> sm = pystan.StanModel(file='ermodel__base.stan', charset='utf-8', verbose=True)
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_e66d773e298cf460136371fe888abe55 NOW.
INFO:pystan:OS: darwin, Python: 3.6.7 | packaged by conda-forge | (default, Nov 20 2018, 18:37:09)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)], Cython 0.29.2
Compiling /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmphgt4_drw/stanfit4anon_model_e66d773e298cf460136371fe888abe55_1021441695274832365.pyx because it changed.
[1/1] Cythonizing /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmphgt4_drw/stanfit4anon_model_e66d773e298cf460136371fe888abe55_1021441695274832365.pyx
building 'stanfit4anon_model_e66d773e298cf460136371fe888abe55_1021441695274832365' extension
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmphgt4_drw/var
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmphgt4_drw/var/folders
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmphgt4_drw/var/folders/x9
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmphgt4_drw/var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmphgt4_drw/var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmphgt4_drw/var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmphgt4_drw
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/daeda/anaconda3/envs/pystanc36/include -arch x86_64 -I/Users/daeda/anaconda3/envs/pystanc36/include -arch x86_64 -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -I/var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmphgt4_drw -Ianaconda3/envs/pystanc36/lib/python3.6/site-packages/pystan -I/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/site-packages/pystan -I/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/site-packages/pystan/stan/src -I/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/site-packages/pystan/stan/lib/stan_math -I/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/site-packages/pystan/stan/lib/stan_math/lib/eigen_3.3.3 -I/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.66.0 -I/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/site-packages/pystan/stan/lib/stan_math/lib/sundials_3.1.0/include -I/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/site-packages/numpy/core/include -I/Users/daeda/anaconda3/envs/pystanc36/include/python3.6m -c /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmphgt4_drw/stanfit4anon_model_e66d773e298cf460136371fe888abe55_1021441695274832365.cpp -o /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmphgt4_drw/var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmphgt4_drw/stanfit4anon_model_e66d773e298cf460136371fe888abe55_1021441695274832365.o -O2 -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from /Users/daeda/anaconda3/envs/pystanc36/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/syslimits.h:7:0,
                 from /Users/daeda/anaconda3/envs/pystanc36/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:34,
                 from /Users/daeda/anaconda3/envs/pystanc36/include/python3.6m/Python.h:11,
                 from /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmphgt4_drw/stanfit4anon_model_e66d773e298cf460136371fe888abe55_1021441695274832365.cpp:58:
/Users/daeda/anaconda3/envs/pystanc36/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
 #include_next <limits.h>  /* recurse down to the real one */
                                                             ^
compilation terminated.
Traceback (most recent call last):
  File "/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/site-packages/pystan/model.py", line 349, in __init__
    build_extension.run()
  File "/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1
```

**Comment by daeh** [comment]
I'm still getting a gcc error with python 3.6 and numpy 1.15.4. I tried all the combinations of setting the development environment and python 3.6/3.7 but seems to produce the same behavior.

```
(pystanc36) ➜ ~🌀 which gcc
/Users/daeda/anaconda3/envs/pystanc36/bin/gcc
(pystanc36) ➜ ~🌀 gcc --version
gcc (GCC) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(pystanc36) ➜ ~🌀 python
Python 3.6.7 | packaged by conda-forge | (default, Nov 20 2018, 18:37:09)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import pystan
>>> import os
>>> import platform
>>> print(platform.system())
Darwin
>>> print(platform.release())
18.2.0
>>> print(pystan.__version__)
2.18.1.0
>>> print(np.__version__)
1.15.4
>>> os.environ['MACOSX_DEPLOYMENT_TARGET'] = '10.9'
>>> sm = pystan.StanModel(file='/Volumes/cristae/samadhi_daeda/coding/-GitRepos/adhder/analysis/behavioral/stanmodels/ermodel__base.stan', charset='utf-8', verbose=True)
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_e66d773e298cf460136371fe888abe55 NOW.
INFO:pystan:OS: darwin, Python: 3.6.7 | packaged by conda-forge | (default, Nov 20 2018, 18:37:09)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)], Cython 0.29.2
Compiling /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmp4pzjmw9t/stanfit4anon_model_e66d773e298cf460136371fe888abe55_4497958443753142621.pyx because it changed.
[1/1] Cythonizing /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmp4pzjmw9t/stanfit4anon_model_e66d773e298cf460136371fe888abe55_4497958443753142621.pyx
building 'stanfit4anon_model_e66d773e298cf460136371fe888abe55_4497958443753142621' extension
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmp4pzjmw9t/var
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmp4pzjmw9t/var/folders
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmp4pzjmw9t/var/folders/x9
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmp4pzjmw9t/var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmp4pzjmw9t/var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T
creating /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmp4pzjmw9t/var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmp4pzjmw9t
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/daeda/anaconda3/envs/pystanc36/include -arch x86_64 -I/Users/daeda/anaconda3/envs/pystanc36/include -arch x86_64 -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -I/var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmp4pzjmw9t -Ianaconda3/envs/pystanc36/lib/python3.6/site-packages/pystan -I/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/site-packages/pystan -I/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/site-packages/pystan/stan/src -I/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/site-packages/pystan/stan/lib/stan_math -I/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/site-packages/pystan/stan/lib/stan_math/lib/eigen_3.3.3 -I/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.66.0 -I/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/site-packages/pystan/stan/lib/stan_math/lib/sundials_3.1.0/include -I/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/site-packages/numpy/core/include -I/Users/daeda/anaconda3/envs/pystanc36/include/python3.6m -c /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmp4pzjmw9t/stanfit4anon_model_e66d773e298cf460136371fe888abe55_4497958443753142621.cpp -o /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmp4pzjmw9t/var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmp4pzjmw9t/stanfit4anon_model_e66d773e298cf460136371fe888abe55_4497958443753142621.o -O2 -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from /Users/daeda/anaconda3/envs/pystanc36/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/syslimits.h:7:0,
                 from /Users/daeda/anaconda3/envs/pystanc36/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:34,
                 from /Users/daeda/anaconda3/envs/pystanc36/include/python3.6m/Python.h:11,
                 from /var/folders/x9/y4r_w7gj4_j_3wkfxn6s6fqm0000gp/T/tmp4pzjmw9t/stanfit4anon_model_e66d773e298cf460136371fe888abe55_4497958443753142621.cpp:58:
/Users/daeda/anaconda3/envs/pystanc36/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
 #include_next <limits.h>  /* recurse down to the real one */
                                                             ^
compilation terminated.
Traceback (most recent call last):
  File "/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/site-packages/pystan/model.py", line 349, in __init__
    build_extension.run()
  File "/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/Users/daeda/anaconda3/envs/pystanc36/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1
```

**Comment by daeh** [comment]
> Can clang be used in this situation instead of gcc?

Is this something that I can try with the current pystan release or does it require a PR?

**Comment by ahartikainen** [comment]
Don't install gcc with conda.

**Comment by ahartikainen** [comment]
Also setting

`CC=clang`

**Comment by daeh** [comment]
Ok, working now. If I don't install gcc, it works on both python 3.6. and 3.7 (with numpy 1.16.0), but only if I set the development environment.

Installing GCC or not setting `os.environ['MACOSX_DEPLOYMENT_TARGET'] = '10.9'` causes a gcc error.

thanks _a ton_ for the help.

**Comment by ahartikainen** [comment]
Hi, great news.

So without gcc --> links against `libc++`

With gcc --> links against `libstdc++` (this is missing now with latest xcode.
