### ISSUE TITLE
windows unsuccessfully installed pystan

### ISSUE THREAD

**Issue by sandy-shirt** [stan-dev/pystan#555]
win10  
python  version 3.6.5
numpy  and Cython are already installed 
pls  help
error message like follows:
```
 Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\situ\AppData\Local\Temp\pip-install-xpaa04mf\pystan\setup.py", line 255, in <module>
        setup_package()
      File "C:\Users\situ\AppData\Local\Temp\pip-install-xpaa04mf\pystan\setup.py", line 244, in setup_package
        dist.run_commands()
      File "c:\program files\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\program files\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\program files\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\program files\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\program files\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\program files\python36\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\program files\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\program files\python36\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
        _build_ext.run(self)
      File "c:\program files\python36\lib\distutils\command\build_ext.py", line 308, in run
        force=self.force)
      File "c:\program files\python36\lib\site-packages\numpy\distutils\ccompiler.py", line 765, in new_compiler
        compiler = klass(None, dry_run, force)
      File "c:\program files\python36\lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 69, in __init__
        dry_run, force)
      File "c:\program files\python36\lib\distutils\cygwinccompiler.py", line 126, in __init__
        if self.ld_version >= "2.10.90":
    TypeError: '>=' not supported between instances of 'NoneType' and 'str'

Command ""c:\program files\python36\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\situ\\AppData\\Local\\Temp\\pip-install-xpaa04mf\\pystan\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\situ\AppData\Local\Temp\pip-record-4zzz6mcq\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\situ\AppData\Local\Temp\pip-install-xpaa04mf\pystan\
```

**Comment by ahartikainen** [comment]
Hi, have you followed our Windows instructions?

https://pystan.readthedocs.io/en/latest/windows.html

**Comment by sandy-shirt** [comment]
> 
> 
> Hi, have you followed our Windows instructions?
> 
> https://pystan.readthedocs.io/en/latest/windows.html

ths, I read the instructions and I installed the MinGW-w64 for windows 
I got the error when I  try pip install pystan again,like this:

C:/Program Files/mingw-w64/x86_64-8.1.0-win32-seh-rt_v6-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/cmath:1121:11: error: '::hypot' has not been declared
       using ::hypot;
               ^~~~~
    error: Command "gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes -DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x1900 -Ic:\program files\python36\include -Ic:\program files\python36\include -c pystan/_misc.cpp -o build\temp.win-amd64-3.6\Release\pystan\_misc.o" failed with exit status 1

Command ""c:\program files\python36\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\situ\\AppData\\Local\\Temp\\pip-install-h4818yfv\\pystan\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\situ\AppData\Local\Temp\pip-record-ysny_31t\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\situ\AppData\Local\Temp\pip-install-h4818yfv\pystan\


could u tell me the reason？

**Comment by ahartikainen** [comment]
Have you added `distutils.cfg`?

You probably need to use mingw-w64 + libpython from conda.

**Comment by sandy-shirt** [comment]
> 
> Have you added `distutils.cfg`?
> 
> You probably need to use mingw-w64 + libpython from conda.

I've added  `distutils.cfg` . There still exist this problem ,  is this  neccessary to use conda  ?
becuase I installed pycharm instead of anaconda. is there any other ways?

**Comment by ahartikainen** [comment]
Vanilla mingw-w64 does not probably work. You need to get msys2 version and then you need libpython file + do the commands found in the installation. (this is manual work and I don't know if it will work),

You can also install miniconda and setup env based on the instructions (either start pycharm with env activated or add compiler folder to PATH) and use that env inside pycharm.

**Comment by ahartikainen** [comment]
Closing due to inactivity. Can be reopened if needed.

**Comment by Quetzalcohuatl** [comment]
Run this `conda install libpython m2w64-toolchain -c msys2`

**Comment by maulberto3** [comment]
@ahartikainen  FYI, it's impossible to install pystan correctly in Windows machines without Anaconda, in turn making it impossible for fbprophet to work. Hopefully, some workaround will happen soon, but Windows users are truly affected.
