### ISSUE TITLE
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

### ISSUE THREAD

**Issue by s144117** [stan-dev/pystan#563]
Hi,
I was running some models and tried to increase the dimensionallity (728D) of the problem. I used 10,000 data-points which weren't enough to constrain the problem, Rhat>1. Then I increased the data size to 100,000 points. But I got the following error:

`Traceback (most recent call last):
  File "/home/micmad/Documents/thesis/standard_run.py", line 62, in <module>
    fit = model.sampling(data=data, seed=194838, iter=post_warm_up+warm_up, warmup = warm_up, chains=chains, control=dict(max_treedepth = treedepth))
  File "/pack/python_3.5.2/lib/python3.5/site-packages/pystan/model.py", line 778, in sampling
    ret_and_samples = _map_parallel(call_sampler_star, call_sampler_args, n_jobs)
  File "/pack/python_3.5.2/lib/python3.5/site-packages/pystan/model.py", line 85, in _map_parallel
    map_result = pool.map(function, args)
  File "/pack/python_3.5.2/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/pack/python_3.5.2/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/pack/python_3.5.2/lib/python3.5/multiprocessing/pool.py", line 385, in _handle_tasks
    put(task)
  File "/pack/python_3.5.2/lib/python3.5/multiprocessing/connection.py", line 206, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/pack/python_3.5.2/lib/python3.5/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
`

Have anyone else experienced this problem?

#### PyStan Version:
2.18.1.0

#### Python Version:
3.5.2

#### Operating System:
Scientific Linux realease 6.10 (Carbon)

**Comment by ahartikainen** [comment]
I think this is a problem with multiprocessing (actually how they use "wrong" pickle protocol) library.

Current solution is to run your code with `n_jobs=1`, which is suboptimal.

PyStan3 does not have this problem.

You could run your code with CmdStan and then read it with ArviZ.

**Comment by ivvv** [comment]
After a couple of weeks running a code based on `pystan` it failed with this error.  Using version `2.17.1.0` and python 3.6.

What do you mean by `PyStan3`? Can you provide a link or more info about it? Never seen it before.
