### ISSUE TITLE
Compile error on (arch) linux

### ISSUE THREAD

**Issue by jikaasik** [stan-dev/pystan#582]
**Issue:**
I can't get the 8 schools example model to compile in pystan. I keep getting the below error. (I ran the model with verbose=TRUE for extra detail below.) Any help would be appreciated! 

**Code I used:**
`import pystan
import numpy
import cython
sm = pystan.StanModel(file='8schools.stan', verbose=True)`

**Versions:**
Python: 3.7.3
GCC: 7.3.0
Cython: 0.29.6

**Output:**
`Compiling /tmp/tmp99hzi21t/stanfit4anon_model_dcbb35b13c0abee9c65358ba6117a952_4218614916219300018.pyx because it changed.
[1/1] Cythonizing /tmp/tmp99hzi21t/stanfit4anon_model_dcbb35b13c0abee9c65358ba6117a952_4218614916219300018.pyx
building 'stanfit4anon_model_dcbb35b13c0abee9c65358ba6117a952_4218614916219300018' extension
creating /tmp/tmp99hzi21t/tmp
creating /tmp/tmp99hzi21t/tmp/tmp99hzi21t
gcc -pthread -B /home/jikaasik/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -I/tmp/tmp99hzi21t -I/home/jikaasik/anaconda3/lib/python3.7/site-packages/pystan -I/home/jikaasik/anaconda3/lib/python3.7/site-packages/pystan/stan/src -I/home/jikaasik/anaconda3/lib/python3.7/site-packages/pystan/stan/lib/stan_math -I/home/jikaasik/anaconda3/lib/python3.7/site-packages/pystan/stan/lib/stan_math/lib/eigen_3.3.3 -I/home/jikaasik/anaconda3/lib/python3.7/site-packages/pystan/stan/lib/stan_math/lib/boost_1.69.0 -I/home/jikaasik/anaconda3/lib/python3.7/site-packages/pystan/stan/lib/stan_math/lib/sundials_4.1.0/include -I/home/jikaasik/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/home/jikaasik/anaconda3/include/python3.7m -c /tmp/tmp99hzi21t/stanfit4anon_model_dcbb35b13c0abee9c65358ba6117a952_4218614916219300018.cpp -o /tmp/tmp99hzi21t/tmp/tmp99hzi21t/stanfit4anon_model_dcbb35b13c0abee9c65358ba6117a952_4218614916219300018.o -O2 -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized -std=c++1y
g++ -pthread -shared -B /home/jikaasik/anaconda3/compiler_compat -L/home/jikaasik/anaconda3/lib -Wl,-rpath=/home/jikaasik/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ /tmp/tmp99hzi21t/tmp/tmp99hzi21t/stanfit4anon_model_dcbb35b13c0abee9c65358ba6117a952_4218614916219300018.o -o /tmp/tmp99hzi21t/stanfit4anon_model_dcbb35b13c0abee9c65358ba6117a952_4218614916219300018.cpython-37m-x86_64-linux-gnu.so

---------------------------------------------------------------------------
DistutilsExecError                        Traceback (most recent call last)
~/anaconda3/lib/python3.7/distutils/unixccompiler.py in link(self, target_desc, objects, output_filename, output_dir, libraries, library_dirs, runtime_library_dirs, export_symbols, debug, extra_preargs, extra_postargs, build_temp, target_lang)
    204 
--> 205                 self.spawn(linker + ld_args)
    206             except DistutilsExecError as msg:

~/anaconda3/lib/python3.7/distutils/ccompiler.py in spawn(self, cmd)
    908     def spawn(self, cmd):
--> 909         spawn(cmd, dry_run=self.dry_run)
    910 

~/anaconda3/lib/python3.7/distutils/spawn.py in spawn(cmd, search_path, verbose, dry_run)
     35     if os.name == 'posix':
---> 36         _spawn_posix(cmd, search_path, dry_run=dry_run)
     37     elif os.name == 'nt':

~/anaconda3/lib/python3.7/distutils/spawn.py in _spawn_posix(cmd, search_path, verbose, dry_run)
    158                           "command %r failed with exit status %d"
--> 159                           % (cmd, exit_status))
    160             elif os.WIFSTOPPED(status):

DistutilsExecError: command 'g++' failed with exit status 1

During handling of the above exception, another exception occurred:

LinkError                                 Traceback (most recent call last)
<ipython-input-3-01d119f5014b> in <module>
----> 1 sm = pystan.StanModel(file='8schools.stan', verbose=True)

~/anaconda3/lib/python3.7/site-packages/pystan/model.py in __init__(self, file, charset, model_name, model_code, stanc_ret, include_paths, boost_lib, eigen_lib, verbose, obfuscate_model_name, extra_compile_args)
    347 
    348         try:
--> 349             build_extension.run()
    350         finally:
    351             if redirect_stderr:

~/anaconda3/lib/python3.7/distutils/command/build_ext.py in run(self)
    338 
    339         # Now actually compile and link everything.
--> 340         self.build_extensions()
    341 
    342     def check_extensions_list(self, extensions):

~/anaconda3/lib/python3.7/distutils/command/build_ext.py in build_extensions(self)
    447             self._build_extensions_parallel()
    448         else:
--> 449             self._build_extensions_serial()
    450 
    451     def _build_extensions_parallel(self):

~/anaconda3/lib/python3.7/distutils/command/build_ext.py in _build_extensions_serial(self)
    472         for ext in self.extensions:
    473             with self._filter_build_errors(ext):
--> 474                 self.build_extension(ext)
    475 
    476     @contextlib.contextmanager

~/anaconda3/lib/python3.7/distutils/command/build_ext.py in build_extension(self, ext)
    557             debug=self.debug,
    558             build_temp=self.build_temp,
--> 559             target_lang=language)
    560 
    561     def swig_sources(self, sources, extension):

~/anaconda3/lib/python3.7/distutils/ccompiler.py in link_shared_object(self, objects, output_filename, output_dir, libraries, library_dirs, runtime_library_dirs, export_symbols, debug, extra_preargs, extra_postargs, build_temp, target_lang)
    715                   libraries, library_dirs, runtime_library_dirs,
    716                   export_symbols, debug,
--> 717                   extra_preargs, extra_postargs, build_temp, target_lang)
    718 
    719 

~/anaconda3/lib/python3.7/distutils/unixccompiler.py in link(self, target_desc, objects, output_filename, output_dir, libraries, library_dirs, runtime_library_dirs, export_symbols, debug, extra_preargs, extra_postargs, build_temp, target_lang)
    205                 self.spawn(linker + ld_args)
    206             except DistutilsExecError as msg:
--> 207                 raise LinkError(msg)
    208         else:
    209             log.debug("skipping %s (up-to-date)", output_filename)

LinkError: command 'g++' failed with exit status 1`

**Comment by ahartikainen** [comment]
What is your compiler version?

**Comment by jikaasik** [comment]
> What is your compiler version?

**g++ --version gives me:** 
g++ (GCC) 8.2.1

**Comment by ahartikainen** [comment]
Can you try this with clean conda env? Let's see if it's something in Anaconda (e.g. Boost library folder)

**Comment by ahartikainen** [comment]
Btw is arch version of gcc compatible with C++14? (Stan 2.19 needs C++14 compatible compiler)

**Comment by jikaasik** [comment]
I tried it on a clean conda environment with no luck. Same result. Regarding Arch's gcc being compatible with C++14, I'm really not sure. I tried figuring that out, but haven't been able to find that answer.

**Comment by Teekuningas** [comment]
You could try installing gxx_linux-64 package to your conda environment. Anaconda ships with custom ld, and your system g++ might be too new for it.

**Comment by ahartikainen** [comment]
Needs c++14 compatible compiler.

Closing due to inactivity. Can be reopened if needed.

**Comment by SpioradObrach** [comment]
I have the same issue under Manjaro Linux

GCC:
gcc version: gcc (GCC) 9.2.0

DISTRIBUTION:
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=18.1.4
DISTRIB_CODENAME=Juhraya
DISTRIB_DESCRIPTION="Manjaro Linux"

TRACEBACK:

`DistutilsExecError                        Traceback (most recent call last)
~/miniconda3/lib/python3.7/distutils/unixccompiler.py in link(self, target_desc, objects, output_filename, output_dir, libraries, library_dirs, runtime_library_dirs, export_symbols, debug, extra_preargs, extra_postargs, build_temp, target_lang)
    204 
--> 205                 self.spawn(linker + ld_args)
    206             except DistutilsExecError as msg:

~/miniconda3/lib/python3.7/distutils/ccompiler.py in spawn(self, cmd)
    909     def spawn(self, cmd):
--> 910         spawn(cmd, dry_run=self.dry_run)
    911 

~/miniconda3/lib/python3.7/distutils/spawn.py in spawn(cmd, search_path, verbose, dry_run)
     35     if os.name == 'posix':
---> 36         _spawn_posix(cmd, search_path, dry_run=dry_run)
     37     elif os.name == 'nt':

~/miniconda3/lib/python3.7/distutils/spawn.py in _spawn_posix(cmd, search_path, verbose, dry_run)
    158                           "command %r failed with exit status %d"
--> 159                           % (cmd, exit_status))
    160             elif os.WIFSTOPPED(status):

DistutilsExecError: command 'g++' failed with exit status 1

During handling of the above exception, another exception occurred:

LinkError                                 Traceback (most recent call last)
~/TEMP_30/stanBase_diagnostics.py in <module>
    260         summary_dict = pickle.load(fhandle)
    261 except FileNotFoundError:       # Fit a new model if failing
--> 262     fit, data = fitmodel()
    263 
    264     with open(filepath, 'wb') as fhandle:

~/TEMP_30/stanBase_diagnostics.py in fitmodel()
    242 
    243     """
--> 244     sm = pystan.StanModel(model_code=model)
    245     def f(x, a=1, b=2, sigma=.5):
    246         y = a * x + b + np.random.randn(x.shape[0]) * sigma

~/miniconda3/lib/python3.7/site-packages/pystan/model.py in __init__(self, file, charset, model_name, model_code, stanc_ret, include_paths, boost_lib, eigen_lib, verbose, obfuscate_model_name, extra_compile_args, allow_undefined, include_dirs, includes)
    376 
    377         try:
--> 378             build_extension.run()
    379         finally:
    380             if redirect_stderr:

~/miniconda3/lib/python3.7/distutils/command/build_ext.py in run(self)
    338 
    339         # Now actually compile and link everything.
--> 340         self.build_extensions()
    341 
    342     def check_extensions_list(self, extensions):

~/miniconda3/lib/python3.7/distutils/command/build_ext.py in build_extensions(self)
    447             self._build_extensions_parallel()
    448         else:
--> 449             self._build_extensions_serial()
    450 
    451     def _build_extensions_parallel(self):

~/miniconda3/lib/python3.7/distutils/command/build_ext.py in _build_extensions_serial(self)
    472         for ext in self.extensions:
    473             with self._filter_build_errors(ext):
--> 474                 self.build_extension(ext)
    475 
    476     @contextlib.contextmanager

~/miniconda3/lib/python3.7/distutils/command/build_ext.py in build_extension(self, ext)
    557             debug=self.debug,
    558             build_temp=self.build_temp,
--> 559             target_lang=language)
    560 
    561     def swig_sources(self, sources, extension):

~/miniconda3/lib/python3.7/distutils/ccompiler.py in link_shared_object(self, objects, output_filename, output_dir, libraries, library_dirs, runtime_library_dirs, export_symbols, debug, extra_preargs, extra_postargs, build_temp, target_lang)
    715                   libraries, library_dirs, runtime_library_dirs,
    716                   export_symbols, debug,
--> 717                   extra_preargs, extra_postargs, build_temp, target_lang)
    718 
    719 

~/miniconda3/lib/python3.7/distutils/unixccompiler.py in link(self, target_desc, objects, output_filename, output_dir, libraries, library_dirs, runtime_library_dirs, export_symbols, debug, extra_preargs, extra_postargs, build_temp, target_lang)
    205                 self.spawn(linker + ld_args)
    206             except DistutilsExecError as msg:
--> 207                 raise LinkError(msg)
    208         else:
    209             log.debug("skipping %s (up-to-date)", output_filename)

LinkError: command 'g++' failed with exit status 1`

**Comment by ahartikainen** [comment]
Hi, please create a new issue if you have problem with different linux distribution.

Compile your model with `verbose=True`, add the output to a file `python myfile.py > out.txt` and find the (first) `error`.

**Comment by SpioradObrach** [comment]
Hi,

Manjaro linux is based on Arch, hence I assume this issue to fit?

I compiled the 

> eightschools.py

example with `verbose=True`, however not all output got piped to the file, not sure why. Relevant first error should be the following:

```status for section .debug_info
/home/user/miniconda3/compiler_compat/ld: /tmp/pystan_461fx_xv/tmp/pystan_461fx_xv/stanfit4anon_model_19a09b474d1901f191444eaf8a6b8ce2_1365422238360713392.o: unable to initialize decompress status for section .debug_info
/home/user/miniconda3/compiler_compat/ld: /tmp/pystan_461fx_xv/tmp/pystan_461fx_xv/stanfit4anon_model_19a09b474d1901f191444eaf8a6b8ce2_1365422238360713392.o: unable to initialize decompress status for section .debug_info
/tmp/pystan_461fx_xv/tmp/pystan_461fx_xv/stanfit4anon_model_19a09b474d1901f191444eaf8a6b8ce2_1365422238360713392.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/home/user/miniconda3/lib/python3.7/distutils/unixccompiler.py", line 205, in link
    self.spawn(linker + ld_args)
  File "/home/user/miniconda3/lib/python3.7/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/user/miniconda3/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/user/miniconda3/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'g++' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eightschools.py", line 27, in <module>
    sm = pystan.StanModel(model_code=schools_code, verbose=True)
  File "/home/user/miniconda3/lib/python3.7/site-packages/pystan/model.py", line 378, in __init__
    build_extension.run()
  File "/home/user/miniconda3/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/user/miniconda3/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/user/miniconda3/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/user/miniconda3/lib/python3.7/distutils/command/build_ext.py", line 559, in build_extension
    target_lang=language)
  File "/home/user/miniconda3/lib/python3.7/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/home/user/miniconda3/lib/python3.7/distutils/unixccompiler.py", line 207, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'g++' failed with exit status 1
```

I guess at this point this is an issue with linked libraries, I'll investigate this. So far I have

- [x] Tried both pip and conda versions of pystan
- [x] Ran `conda update --all`
- [x] Tried different Stan fitting problems

**Comment by SpioradObrach** [comment]
Okay works fine now when using your tip of [Issue 395](https://github.com/stan-dev/pystan/issues/395) to use

`conda create -n stan python=3.6 pystan` (instead of python 3.7 which I currently usually use).

Still I wonder where these issues come from.

**Comment by ahartikainen** [comment]
There must be something missing from python 3.7 on arch. That is really bizarre error.

**Comment by SpioradObrach** [comment]
Potentially some incompatibilities, false linking or so. I'll check from time to time on python 3.4 again
