### ISSUE TITLE
Fatal error in the compiler, using Visual Studio build tools on win10

### ISSUE THREAD

**Issue by knudsvik** [stan-dev/pystan#591]
#### Summary:
After installing pystan, I want to verify the installation like described in the [pystan documentation](https://pystan.readthedocs.io/en/latest/windows.html). When running the line below, I get a fatal error

`model = pystan.StanModel(model_code=model_code)`

#### Current Output:
```
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_5944b02c79788fa0db5b3a93728ca2bf NOW.
WARNING:pystan:MSVC compiler is not supported
stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_1614473494997213468.cpp
C:\Appl\myenv\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/rev/mat/meta/operands_and_partials.hpp(42): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/rev/mat/meta/operands_and_partials.hpp(155): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/prim/mat/meta/seq_view.hpp(145): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/prim/mat/fun/multiply_lower_tri_self_transpose.hpp(19): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
        with
        [
            Derived=Eigen::Matrix<double,-1,-1,0,-1,-1>
        ]
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/prim/mat/fun/multiply_lower_tri_self_transpose.hpp(27): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
        with
        [
            Derived=Eigen::Matrix<double,-1,-1,0,-1,-1>
        ]
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/prim/mat/fun/csr_u_to_z.hpp(28): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/prim/mat/fun/matrix_exp_action_handler.hpp(118): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/prim/mat/fun/to_matrix.hpp(136): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/prim/mat/fun/to_row_vector.hpp(31): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/prim/mat/fun/to_vector.hpp(31): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/prim/mat/fun/welford_covar_estimator.hpp(31): warning C4244: 'return': conversion from 'double' to 'int', possible loss of data
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/prim/mat/fun/welford_var_estimator.hpp(31): warning C4244: 'return': conversion from 'double' to 'int', possible loss of data
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/rev/scal/fun/bessel_first_kind.hpp(19): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/rev/scal/fun/bessel_first_kind.hpp(20): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/rev/scal/fun/bessel_second_kind.hpp(19): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/rev/scal/fun/bessel_second_kind.hpp(20): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/rev/scal/fun/modified_bessel_first_kind.hpp(19): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/rev/scal/fun/modified_bessel_first_kind.hpp(20): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/rev/scal/fun/modified_bessel_second_kind.hpp(19): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/rev/scal/fun/modified_bessel_second_kind.hpp(20): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/rev/scal/fun/rising_factorial.hpp(18): warning C4244: 'argument': conversion from 'double' to 'int', possible loss of data
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/rev/mat/fun/cholesky_decompose.hpp(82): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
        with
        [
            Derived=Eigen::Matrix<stan::math::var,-1,-1,0,-1,-1>
        ]
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/rev/mat/fun/cholesky_decompose.hpp(194): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
        with
        [
            Derived=Eigen::Matrix<stan::math::var,-1,-1,0,-1,-1>
        ]
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/rev/mat/fun/log_softmax.hpp(104): warning C4244: 'argument': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
        with
        [
            Derived=Eigen::Matrix<stan::math::var,-1,1,0,-1,1>
        ]
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/rev/mat/fun/multiply_lower_tri_self_transpose.hpp(21): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
        with
        [
            Derived=Eigen::Matrix<stan::math::var,-1,-1,0,-1,-1>
        ]
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/rev/mat/fun/multiply_lower_tri_self_transpose.hpp(22): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'int', possible loss of data
        with
        [
            Derived=Eigen::Matrix<stan::math::var,-1,-1,0,-1,-1>
        ]
C:\Appl\myenv\lib\site-packages\pystan\stan\lib\stan_math\stan/math/rev/mat/functor/adj_jac_apply.hpp(410): fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'msc1.cpp', line 1527)
 To work around this problem, try simplifying or changing the program near the locations listed above.
Please choose the Technical Support command on the Visual C++
 Help menu, or open the Technical Support help file for more information
Internal Compiler Error in C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.20.27508\bin\HostX86\x64\cl.exe.  You will be prompted to send an error report to Microsoft later.
Traceback (most recent call last):
  File "C:\appl\Python36\lib\distutils\_msvccompiler.py", line 423, in compile
    self.spawn(args)
  File "C:\appl\Python36\lib\distutils\_msvccompiler.py", line 542, in spawn
    return super().spawn(cmd)
  File "C:\appl\Python36\lib\distutils\ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "C:\appl\Python36\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:\appl\Python36\lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.20.27508\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Appl\myenv\lib\site-packages\pystan\model.py", line 349, in __init__
    build_extension.run()
  File "C:\appl\Python36\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\appl\Python36\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "C:\appl\Python36\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\appl\Python36\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "C:\appl\Python36\lib\distutils\_msvccompiler.py", line 425, in compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.20.27508\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
```

#### PyStan Version:
2.19.0.0
#### Python Version:
3.6.7
#### Operating System:
Windows 10

**Comment by ahartikainen** [comment]
In the docs:

> MSVC compiler is not supported.

So currently, MicroSoft Visual Compiler is not supported. You need to use mingw-w64.

**Comment by knudsvik** [comment]
Ok, I am having troubles installing the mingw-w64 on my work PC (Error message: Cannot download repository.txt) so I hoped this could do it. No other compilers than mingw-w64 works?

**Comment by ahartikainen** [comment]
You need to use conda package manager as said in the docs.

I, for example, use miniconda installed on my local folder and create conda envs like described in the docs.

**Comment by ahartikainen** [comment]
Closing due to inactivity. Can be reopened if needed.
