### ISSUE TITLE
following error occurred when i tried to run chat bot code

### ISSUE THREAD

**Issue by changchethu** [stan-dev/pystan#592]
Traceback (most recent call last):
  File "C:\Users\Chethan\Downloads\Beta.py", line 1, in <module>
    from chatterbot import ChatBot
  File "C:\Users\Chethan\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\__init__.py", line 4, in <module>
    from .chatterbot import ChatBot
  File "C:\Users\Chethan\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\chatterbot.py", line 2, in <module>
    from chatterbot.storage import StorageAdapter
  File "C:\Users\Chethan\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\storage\__init__.py", line 1, in <module>
    from chatterbot.storage.storage_adapter import StorageAdapter
  File "C:\Users\Chethan\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\storage\storage_adapter.py", line 3, in <module>
    from chatterbot.tagging import PosHypernymTagger
  File "C:\Users\Chethan\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\tagging.py", line 8, in <module>
    import spacy
  File "C:\Users\Chethan\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\__init__.py", line 12, in <module>
    from .cli.info import info as cli_info
  File "C:\Users\Chethan\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\cli\__init__.py", line 6, in <module>
    from .train import train  # noqa: F401
  File "C:\Users\Chethan\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\cli\train.py", line 18, in <module>
    from ..gold import GoldCorpus
  File "strings.pxd", line 23, in init spacy.gold
ImportError: DLL load failed: The specified module could not be found.

**Comment by ahartikainen** [comment]
How is this related to PyStan?
