### ISSUE TITLE
CentOS 7 - distutils.errors.CompileError: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by CaveDann** [stan-dev/pystan#627]
#### Summary:
OS: CentOS 7 (kernel 3.10.0-957.el7.x86_64)
Python Version: 3.6.2
Numpy Version: 1.16.4
Cython Version: 0.29.12
PyStan Version: 2.19.0.0
/usr/bin/gcc Version: 4.8.5 20150623 (Red Hat 4.8.5-36)

Python start message. 
Python 3.6.2 |Anaconda, Inc.| (default, Oct  5 2017, 07:59:26) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 

I've checked the other threads on this issue and installed following the instructions in the doc, but it produces a ggc failed with exit status 1 error. 

I'm not sure if the start message showing GCC 7.2.0 on linux is a red herring or if that is the source of the underlying problem here.

#### Description:
When trying to run the Eight Schools example, python returns two exceptions.  

distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

distutils.errors.CompileError: command 'gcc' failed with exit status 1

#### Reproducible Steps:
Create the conda environment.
    conda create --name stan_env_362 python=3.6.2 numpy cython

Change into the env.
    source activate stan_env_362

Remove GCC so that 'which gcc' returns /usr/bin/gcc .
    conda remove gcc

Install PyStan using pip. 
    pip install pystan

Attempt to run Eight Schools example. 
    python ./PyStan-Schools.py

#### Current Output:

INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_19a09b474d1901f191444eaf8a6b8ce2 NOW.
Traceback (most recent call last):
  File "/net/workstation/work/CD/.conda/envs/stan_env_362/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/net/workstation/work/CD/.conda/envs/stan_env_362/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/net/workstation/work/CD/.conda/envs/stan_env_362/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/net/workstation/work/CD/.conda/envs/stan_env_362/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./PyStan-Schools.py", line 27, in <module>
    sm = pystan.StanModel(model_code=schools_code)
  File "/net/workstation/work/CD/.conda/envs/stan_env_362/lib/python3.6/site-packages/pystan/model.py", line 349, in __init__
    build_extension.run()
  File "/net/workstation/work/CD/.conda/envs/stan_env_362/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/net/workstation/work/CD/.conda/envs/stan_env_362/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/net/workstation/work/CD/.conda/envs/stan_env_362/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/net/workstation/work/CD/.conda/envs/stan_env_362/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/net/workstation/work/CD/.conda/envs/stan_env_362/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/net/workstation/work/CD/.conda/envs/stan_env_362/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

#### PyStan Version:
2.19.0.0

#### Python Version:
3.6.2

#### Operating System:
CentOS 7 (kernel 3.10.0-957.el7.x86_64)

**Comment by ahartikainen** [comment]
Your gcc (4.8.5) compiler is too old. Stan needs C++1y (C++14) compatible compiler.

gcc 7 is the compiler used to compile your python.

See C++ section in https://github.com/stan-dev/pystan/blob/develop/doc/installation_beginner.rst

e.g. (You can try to set-up conda compiler)

**Comment by CaveDann** [comment]
Thanks for the help. I'll take a look and post to confirm it's made the issue go away. 

Not doubting you, just always useful to have these definitely closed off as solved right?

**Comment by CaveDann** [comment]
Almost a week later and we've still not had much luck with this.

IMHO, I think it's a user error and not a bug. It's likely we've not got the paths quite right for using GCC. 

I'll close this off here. 

Thanks for the response. 
CD

**Comment by ahartikainen** [comment]
Try to export path to bin containing gcc to $PATH
