### ISSUE TITLE
failed with prophet and pystan

### ISSUE THREAD

**Issue by qrdbr** [stan-dev/pystan#644]
**Summary:**

Can not install fbprophet 

**Description:**
I get the following error when I try to install fbprophet.

```
Installing collected packages: fbprophet
  Running setup.py install for fbprophet ... error
    Complete output from command C:\Users\denis\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\denis\\AppData\\Local\\Temp\\pip-install-nlh6crfh\\fbprophet\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\denis\AppData\Local\Temp\pip-record-htz7ixhf\install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\fbprophet
    creating build\lib\fbprophet\stan_model
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\denis\AppData\Local\Temp\pip-install-nlh6crfh\fbprophet\setup.py", line 120, in <module>
        """
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\denis\AppData\Local\Temp\pip-install-nlh6crfh\fbprophet\setup.py", line 44, in run
        build_stan_model(target_dir)
      File "C:\Users\denis\AppData\Local\Temp\pip-install-nlh6crfh\fbprophet\setup.py", line 27, in build_stan_model
        from pystan import StanModel
      File "C:\Users\denis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pystan\__init__.py", line 9, in <module>
        from pystan.api import stanc, stan
      File "C:\Users\denis\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pystan\api.py", line 13, in <module>
        import pystan._api  # stanc wrapper
    ImportError: DLL load failed:  The specified module could not be found.

    ----------------------------------------
Command "C:\Users\denis\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\denis\\AppData\\Local\\Temp\\pip-install-nlh6crfh\\fbprophet\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\denis\AppData\Local\Temp\pip-record-htz7ixhf\install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in C:\Users\denis\AppData\Local\Temp\pip-install-nlh6crfh\fbprophet\
You are using pip version 19.0.3, however version 19.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

#### Reproducible Steps:
I tried to install python  - OK
I tried to install pystan - OK
I tried to install fbprophet - NOK

#### Current Output:
   import pystan._api  # stanc wrapper
    ImportError: DLL load failed:  The specified module could not be found.

#### Expected Output:
I want to be able to install properly working fbprophet .

#### PyStan Version:
pystan             2.19.0.0

#### Python Version:
Python 3.7.4

#### Operating System:
Windows 10 Pro

**Comment by ahartikainen** [comment]
Hi, you need to use conda based python (and compilers ) to use pystan on Windows.

https://pystan.readthedocs.io/en/latest/windows.html

**Comment by qrdbr** [comment]
> Hi, you need to use conda based python (and compilers ) to use pystan on Windows.
> 
> https://pystan.readthedocs.io/en/latest/windows.html

Thanks!!!
