### ISSUE TITLE
Failed to build pystan with Docker

### ISSUE THREAD

**Issue by bigredbug47** [stan-dev/pystan#647]
Hi guys,

I have tried to build pystan in Docker but it occurred errors. I have researched and installed many packages but it still doesn't work.

Here is my Docker file:

```
FROM ubuntu:18.10

ENV HOME /root
ENV PYTHONPATH "/usr/lib/python3/dist-packages:/usr/local/lib/python3.6/site-packages"
RUN apt-get update -y 
RUN apt-get install -y build-essential
RUN apt-get install -y python3 python3-dev python3-pip
RUN apt-get -y install libssl-dev libffi-dev libjpeg-dev libpq-dev libldap2-dev libsasl2-dev libxml2-dev libxslt1-dev libcurl4-openssl-dev libsqlite3-dev libvirt-dev lib32ncurses5-dev libblas-dev liblapack-dev libmpich-dev

RUN pip3 install numpy
RUN pip3 install --trusted-host pypi.python.org pystan

CMD python3 --version
CMD python3 pystan_test.py 
```
Here is my test scripts:

```
import pystan
model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
model = pystan.StanModel(model_code=model_code)  # this will take a minute
y = model.sampling(n_jobs=1).extract()['y']
output = y.mean()  # should be close to 0
print(output)
```

Here is the error output:

```
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_5944b02c79788fa0db5b3a93728ca2bf NOW.
Traceback (most recent call last):
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pystan_test.py", line 27, in <module>
    core_process()
  File "pystan_test.py", line 17, in core_process
    model = pystan.StanModel(model_code=model_code)  # this will take a minute
  File "/usr/local/lib/python3.6/dist-packages/pystan/model.py", line 349, in __init__
    build_extension.run()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

My python version is 3.6, my pystan version is 2.19
Thank you.

**Comment by ahartikainen** [comment]
Can you add `verbose` to `pystan.StanModel(model_code=model_code)`

Does this work `CMD pystan --version`?

**Comment by bigredbug47** [comment]
Hi @ahartikainen,
Sorry, I have deleted the CMD pystan --verion line.

I have change my code from `model = pystan.StanModel(model_code=model_code)` to `model = pystan.StanModel(model_code=model_code, **verbose=True**)`

But it still returns this errors: 

```
x86_64-linux-gnu-gcc: fatal error: Killed signal terminated program cc1plus
compilation terminated.
Traceback (most recent call last):
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demand_forecasting.py", line 27, in <module>
    core_process()
  File "demand_forecasting.py", line 17, in core_process
    model = pystan.StanModel(model_code=model_code, verbose=True)  # this will take a minute
  File "/usr/local/lib/python3.6/dist-packages/pystan/model.py", line 349, in __init__
    build_extension.run()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

Thank you.

**Comment by ahartikainen** [comment]
Do you see any C++ errors?

**Comment by ahartikainen** [comment]
Here is one example that works (Uses `FROM conda/miniconda3` --> `python` is Python 3.x)

https://github.com/arviz-devs/arviz/blob/master/scripts/Dockerfile

Which installs pystan in 

https://github.com/arviz-devs/arviz/blob/master/scripts/create_testenv.sh

**Comment by bigredbug47** [comment]
@ahartikainen that all of the errors display after the very long log in cmd. I will try the example, but what happened with my Docker file, is it missing something?
